### ISSUE TITLE
Pearl of the Void cancels night vision from Treasure Hunter Charm

### ISSUE THREAD

**Issue by grundyboy34** [Extegral/Enigmatic-Legacy#100]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.7.3
 * Curios API: 4.0.2.0
 * Patchouli: 1.16.2-47
 * Forge: 34.1.35

#### Description of a Bug:
Using the Pearl of the Void spellstone alongside the Charm of Treasure Hunter results in the night vision not working do to the Pearl cancelling it.
Is this intended behavior? I think it'd be a great combo if this is fixed.

#### How to Reproduce:
1. Equip both Pearl of the Void & Charm of Treasure Hunter
2. Go Below Y = 50, notice there's no night vision.
3. Unequip Pearl of the Void, notice there's now night vision.

**Comment by Aizistral** [comment]
I did not think about this interaction before, but I cannot say it is unintended. Pearl of the Void is supposed to provide immunity to ANY status effects, including those obtained through means other than potions. In turn, Night Vision provided by Charm of the Treasure Hunter is just another status effect and it is explicitly worded as such in it's tooltip.

However, I think I will make an exception in spite of consistency, simply for convenience of use.

**Comment by grundyboy34** [comment]
Thanks, I'm looking forward to that!  Perhaps you could use a whitelist/blacklist in the config so we can allow whatever potion effects we may want to work with it?

**Comment by Aizistral** [comment]
> Perhaps you could use a whitelist/blacklist in the config so we can allow whatever potion effects we may want to work with it?

Perhaps. My config implementation does still need work to support type arrays, and I will need a parser on top of that to comprehend blacklists/whitelists for stuff. Once it's all there I will consider.
