### ISSUE TITLE
New worlds have default name changed

### ISSUE THREAD

**Issue by Lykrast** [Extegral/Enigmatic-Legacy#101]
#### Versions:
 * Enigmatic Legacy: 2.9.0
 * Curios API: 4.0.2.0
 * Patchouli: 47
 * Forge: 1.16.**4** - 35.0.1

#### Bug:
Enigmatic Legacy changes the name of new created worlds to be World #(random numbers) instead of New World, which looks like to be a dev feature that may have been left on. The random numbers change every time.

![2020-11-06_21 55 35](https://user-images.githubusercontent.com/8684850/98414300-66a3a900-207b-11eb-84a0-491805025a4e.png)

I tested this with only Curios, Patchouli, and Enigmatic Legacy, where it happens, then without Enigmatic Legacy and the worlds were named New World by default as intended.

**Comment by Aizistral** [comment]
It is intended feature, designed to solve many people's problem of stockpiling infinite "New World"s, by giving each new world unique and perfectly discernable name (no sarcasm intended). You can disable it in `enigmaticlegacy-client.omniconf` within `config` folder in your Minecraft directory if you don't like it for whatever reason.

**Comment by Lykrast** [comment]
I feel like at least the mod page should explicitely mention this feature, since it's not something everyone wants. And if someone doesn't want it, it can be really hard to pinpoint what config to change in a crowded modpack as it is not obvious at all that this exploration/baubles mod would add such a feature. At least I'm sure this mod would not be the first place 99% of people would look to disable this.

**Comment by Aizistral** [comment]
I have asked a couple other people's opinion on the matter, and, well, they indeed confirmed that such feature isn't anything anyone would expect to be in Enigmatic Legacy, even though most don't mind it being there. I currently consider between leaving it off by default or moving it into separate mod like it once was.

**Comment by Lykrast** [comment]
Personally, I would suggest separate mod. Because then people that want this feature can have it without Enigmatic Legacy, and also can easily find it if they're looking for it (since they probably would not be looking in Enigmatic Legacy's config for that feature).

Either way is fine for me though, but it's just one opinion so do as you want if you have other people with valid opinions you wanna ask.
