### ISSUE TITLE
Can'r go to sleep

### ISSUE THREAD

**Issue by Calsifer** [Extegral/Enigmatic-Legacy#105]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:2.7.1
 * Curios API:4.0.2.0
 * Patchouli:2-44
 * Forge:2.1.2

#### Description of a Bug:
Playing on multiplayer server with friends, what you wear ring of 7 courses you going to bed does not work. We have Morpheus-1.16.3-4.2.63 version installed. Everyone else who does not wear this ring has no issues. 

#### How to Reproduce:
1. ... Wear 7 courses ring
2. ... Go to bed with Morpheus-1.16.3-4.2.63 mod and someone else on the server
3. ... Nothing happens
4. Behold!

#### Logs:
No crash logs for this one

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
Okay, what do you mean by "nothing happens"? What did you expect to happen, for that matter?

**Comment by Calsifer** [comment]
nvm I didn't read the full description
