### ISSUE TITLE
[Question] Blacklisting neutral entities for Ring of the Seven Curses

### ISSUE THREAD

**Issue by drakray** [Extegral/Enigmatic-Legacy#106]
**The question.**
Like the title say, is there a way to blacklist certain neutral entities from becoming auto-aggressive when wearing the Ring?
I mainly have in mind Guard from [Guard Villagers](https://www.curseforge.com/minecraft/mc-mods/guard-villagers) (naturally spawned and player-promoted) and maybe some Golem from [ExtraGolem](https://www.curseforge.com/minecraft/mc-mods/extra-golems) (when spawned naturally in village, player created one are always passive), but could be useful for packMaker in general who might want control to manage mod interaction.

**Comment by Aizistral** [comment]
There isn't a way yet, but it is planned and will be there soon.
