### ISSUE TITLE
Crash upon mob hit.

### ISSUE THREAD

**Issue by Capt-efficiency** [Extegral/Enigmatic-Legacy#110]
I was making my way through a Dungeoncrawl dungeon, when I was hit by a wither skelly from a mob spawner. I got hit once and then the game crashed. I opened the crash log and it said something about enigmatic legacy...

[crash-2020-11-23_13.52.12-server.txt](https://github.com/Extegral/Enigmatic-Legacy/files/5581043/crash-2020-11-23_13.52.12-server.txt)

I am using the latest version of your mod, running the modpack TNP Limitless 3 (16.4 minecraft).

Thanks.

**Comment by Aizistral** [comment]
Please create your issue again using bug report template: [Click This](https://github.com/Extegral/Enigmatic-Legacy/issues/new?assignees=Extegral&labels=bug%2C+awaits+review&template=bug-report.md&title=)
It's not there just as a decoration, you know. If you can't reproduce this crash outside of modpack no worries, but would be appreciatable if you at least tried to.
