### ISSUE TITLE
Crash upon equip Void spellstone

### ISSUE THREAD

**Issue by aburone** [Extegral/Enigmatic-Legacy#113]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: EnigmaticLegacy-2.10.0.jar
 * Curios API: curios-forge-1.16.4-4.0.2.1.jar
 * Patchouli: Patchouli-1.16.4-48.jar
 * Forge: 35.0.16

#### Description of a Bug:
Crash to desktop when equipping the void spellstone in the nether.
I had several vexes around me at the time and had also the "water" (can't remember the name now) spellstone equipped in another curios slot

[crash-2020-12-01_20.10.26-client.txt](https://github.com/Extegral/Enigmatic-Legacy/files/5626003/crash-2020-12-01_20.10.26-client.txt)

**Comment by Aizistral** [comment]
Here is another example of why that bug report template kindly asks you to reproduce your issue without other mods first, and you have like a ton of those in your modpack.

The crash happens somewhere in the code of Potions Master. Report it to their issue tracker: [https://www.curseforge.com/minecraft/mc-mods/potionsmaster/issues](https://www.curseforge.com/minecraft/mc-mods/potionsmaster/issues)

**Comment by aburone** [comment]
I can't disable every mod. That would eliminate all my items. The crash doesn't happens all the time so I can't be prepared for it.
Reported to potions masters

**Comment by Aizistral** [comment]
> I can't disable every mod. That would eliminate all my items. 

Look, you don't have to load up your survival world or something with those mods disabled. Worst case you can just create separate MC installation for testing things, though usually there's not much reason to.

> The crash doesn't happens all the time so I can't be prepared for it.

This is what debugging should be done for in front of reporting anything to mod developers. It might not be easy to figure out the circumstances under which one or another bug takes place, but it's no excuse for never attempting that at all.
