### ISSUE TITLE
Gift of the heaven does not take effect

### ISSUE THREAD

**Issue by wjzczzjl2020** [Extegral/Enigmatic-Legacy#114]
Latest version

Gift of the haven doesn't work. You can't take off by double clicking on a space. You will also be hurt by falling

I remember that in the past, both of these can be implemented. Are they bugs or changes?

**Comment by Aizistral** [comment]
> (be specific, do not write "latest")

Create issue using proper bug report template. Issues written with disregard to that template shall no longer be reviewed.

**Comment by wjzczzjl2020** [comment]
Versions: 
* Enigmatic Legacy:Enigmatic Legacy-2.10.0
 * Curios API:curios-forge-1.16.4-4.0.3.0
 * Patchouli:Patchouli-1.16.4-48.jar
 * Forge:1.16.4-35.1.0

Description of a Bug:
Gift of the haven can't take off by double clicking on a space

How to Reproduce:
Make gift of the haven and equip it, then double-click the space

**Comment by Aizistral** [comment]
My tests do not confirm your claim to be the case. Make sure you are in the range of an active Beacon and have experience in order to be able to fly.
