### ISSUE TITLE
[Suggestion] Config option to disable enchantments.

### ISSUE THREAD

**Issue by Inpaladin** [Extegral/Enigmatic-Legacy#116]
Title.  I feel like it'd be nice to have the ability to disable certain enchantments added by this mod, for the sake of balance in a modpack.  This is obviously totally subjective, hence this being a call for a config option and not a nerf, but I feel that torrent and slayer feel slightly redundant and that the crossbow enchants make regular bows redundant.

**Comment by Aizistral** [comment]
Implemented in 2.11.7.
