### ISSUE TITLE
Crash at the start 2.0

### ISSUE THREAD

**Issue by DamienBrittan** [Extegral/Enigmatic-Legacy#119]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: EnigmaticLegacy-2.10.1
 * Curios API:curios-forge-1.16.4-4.0.3.0
 * Patchouli:Patchouli-1.16.4-48
 * Forge:35.1.13

#### Description of a Bug:
After adding this mod to mod folder i am having a crash when trying to open the game 

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/yacocewifi.sql).

**Comment by Aizistral** [comment]
According to the crash log, you have the exact same issue as in #115.
