### ISSUE TITLE
A possibity in config to not give Seven Curses and the other ring at the Spawn of player ?

### ISSUE THREAD

**Issue by Switch-Back18** [Extegral/Enigmatic-Legacy#126]
**Provide a detailed and clear description of feature or change that you want to offer.**
It could be good to choose if the spawn ring be give at the first spawn to give them with quests or other !

**Describe why you want this. If there's a reason.**
In the config file a line with SevenCurse in firstspawn : true / false
and the same for the other ring 

It can be good for pack making ^^

Thanks you

**Comment by Aizistral** [comment]
You can disable Enigmatic Amulet and Ring of the Seven Curses in accessibility config. That will prevent them from being granted to player upon entering new world.

**Comment by Switch-Back18** [comment]
Can we give this after with quests or other with this config ?

**Comment by Aizistral** [comment]
Yes. No items themselves are not removed from the mod when you disable them in accessibility config, it's just supposed to make them unobtainable, for instance so that modpack developers could make their own recipes or ways of obtaining certain things.
