### ISSUE TITLE
Newest version of the mod 10.3 keeps crashing the old world with the version 10.2 previously installed.

### ISSUE THREAD

**Issue by TerranE5** [Extegral/Enigmatic-Legacy#127]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.10.3
 * Curios API: _Irrelevant_
 * Patchouli: _Irrelevant_
 * Forge: _Irrelevant_

#### Description of a Bug:
Ok so this bug is an annoying and a very serious one at that. When you previously have played the world with the 10.2 version of the mod and decided to update it with the new 10.3 version, the world will immediately black out and kick you out of the game for no reason. I have at least 52 mods installed. Some of which is ice and fire, wyrmroost, undergarden, biomes you go, guard villagers, many more, etc.

#### How to Reproduce:
1. Install the newest version (10.3)
2. Play the existing world that was previously opened with 10.2 version
3. Watch the game quit itself trying to identify what happened.
4. Behold! Bug.

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
I need you to provide either crash report, or ideally your `latest.log` file. Paste it on site like [Hastebin](https://hastebin.com/) and come back here with the link.

**Comment by TheWitherlord** [comment]
I think I might be getting the same crash, but I have a log.

https://gist.github.com/TheWitherlord/374aec7f00fead2a9e43b973ca2387fe

**Comment by TheWitherlord** [comment]
I tried to update it with the debug but it was so long I guess the Gist couldn't keep up.

**Comment by Aizistral** [comment]
@TheWitherlord, your log indicates Spartan Weaponry as the mod behind unnamed LootPool. I have already reported an issue to them: https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry/issues/161

Try to update Spartan Weaponry in your modpack to 2.1.0-beta-2 and see if it helps.

**Comment by Aizistral** [comment]
Closing this as stale since no reply followed from original author.
