### ISSUE TITLE
Could you include your build.gradle, gradle properties, wrapper, etc, in the repository?

### ISSUE THREAD

**Issue by duely** [Extegral/Enigmatic-Legacy#13]
I noticed that the hammer doesn't have the 3x3 overlay and was going to offer in a PR the code I wrote for Compacted (based off concepts from older 1.12 models) that show block break particles and a block selection overlay, but without the gradle file it would be very difficult for me to set up a working environment in which I could compile the mod.

**Comment by Extegral** [comment]
Guess I can. Haven't thought someone will ever need that, honestly.

**Comment by duely** [comment]
Thanks! you'll also need to add the gradle folder that has the default wrapper inside of it. Much appreciated though, I'll try to get that PR in now.

**Comment by Extegral** [comment]
Done.
