### ISSUE TITLE
Problem crash player in server

### ISSUE THREAD

**Issue by RedneTwo** [Extegral/Enigmatic-Legacy#136]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: EnigmaticLegacy-2.10.3
 * Curios API: curios-forge-1.16.4-4.0.3.4
 * Patchouli: Patchouli-1.16.4-48
 * Forge: 1.16.4-forge-35.1.36

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. Create a server for 2 players
2. A player must have items in their inventory and die
3. When he returns to the grave and the other player is looking at his grave, he will crash the person looking at him (not the one who died)
4. Behold!

#### Logs:

Crash Log: [https://pastebin.com/VFzy9WPF](https://pastebin.com/VFzy9WPF).

**Comment by Aizistral** [comment]
I need you to provide crash report file at least, or your full `.log` file. I can't figure out much just by looking at that stacktrace.

**Comment by noolaan** [comment]
Bump. Seems like an incompatibility with Optifine when rendering particles.
[Full Log Here](https://cdn.discordapp.com/attachments/395705701093212161/802389900938575912/2021-01-22-1.log)

**Comment by RedneTwo** [comment]
is there any way to solve it without removing optifine?

**Comment by RedneTwo** [comment]
Likewise add an option in the config to be able to disable grave / soul

**Comment by Aizistral** [comment]
I will fix this on my side when I get time around to confirm it and figure out what might be the cause. Await.
