### ISSUE TITLE
Unholy Grail CTD while on server

### ISSUE THREAD

**Issue by WanderingFade** [Extegral/Enigmatic-Legacy#137]
When a player drinks from Unholy Grail while on server this results in a "Saving" Screen and then CTD afterwards MC gives the attached crashlog.

[crash-2021-01-16_07.40.20-client.txt](https://github.com/Extegral/Enigmatic-Legacy/files/5824481/crash-2021-01-16_07.40.20-client.txt)

**Comment by WanderingFade** [comment]
Enigmatic Legacy: EnigmaticLegacy-2.10.3
Curios API: curios-forge-1.16.4-4.0.3.5
Patchouli: Patchouli-1.16.4-48
Forge: 1.16.4-forge-35.1.36

Error states that it is a Ticking entity error and the player had a Blazing core equipped which speeds up tick rate, possibly related? Player still gets the crash error after server restart and seems to have some effects from the grail applied to them when they log back in (Lowered hunger, no potion effects)

Recreated by a player removing the Grail from the applied energistics computer storage and drinking it.

**Comment by Aizistral** [comment]
Any submitted bug reports that do not use and follow bug report template will not be reviewed. Please create another issue, following the template and properly filling in all requested data: https://github.com/Extegral/Enigmatic-Legacy/issues/new?assignees=Extegral&labels=bug%2C+awaits+review&template=bug-report.md&title=
