### ISSUE TITLE
Starting trinkets do not spawn in a pre-existing world

### ISSUE THREAD

**Issue by tavanuka** [Extegral/Enigmatic-Legacy#139]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.10.3
 * Curios API: 1.16.4-4.0.3.0
 * Patchouli: 1.16.4-48
 * Forge: 35.1.28

#### Description of a Bug:
The starting amulet and the ring of seven curses is not bestowed upon the player when entering an existing world, despite the player having free inventory space.

#### How to Reproduce:
1. Create a world without the mod installed, let it generate
2. Save, and exit the world. Close the client
3. Install the mod, and launch the same world again.
4. Behold!

#### Logs:
none-

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
Could not reproduce this with Forge 36.0.54 using Enigmatic Legacy 2.10.3, on 1.16.5. Are you sure you have no other mods besides direct dependencies in your environment?
