### ISSUE TITLE
Angel's Blessing projectiles redirection nerf

### ISSUE THREAD

**Issue by slowiu06** [Extegral/Enigmatic-Legacy#14]
As I tested it seems a bit overpowered. I thought about configurable chance of redirection. Or at least make it to work only on distance (so skeltons can hit us from close range).

**Comment by Extegral** [comment]
I'll consider.

**Comment by slowiu06** [comment]
I have used this item a little longer and in fact its capabilities are too high. I also thought that such an advantage could have an equally big disadvantage, in this case preventing us from launching projectiles, we are left with a sword in hand.

**Comment by Aizistral** [comment]
Took me only two minecraft updates to implement this. I am speed!
