### ISSUE TITLE
Blazing Core crashing in certain cases

### ISSUE THREAD

**Issue by WanderingFade** [Extegral/Enigmatic-Legacy#143]
#### Versions (Be specific, do not write "latest"):
 *Enigmatic Legacy: EnigmaticLegacy-2.10.3
 *Curios API: curios-forge-1.16.4-4.0.3.5
 *Patchouli: Patchouli-1.16.4-48
 *Forge: 1.16.4-forge-35.1.36
 *Refined Storage: refinedstorage-1.9.11.jar

#### Description of a Bug:
When a player drinks from Unholy Grail while on the server this results in a "Saving" Screen and then CTD. Afterwards MC gives the attached crashlog.

#### How to Reproduce:
1. Be on hosted server
2. Remove the Grail from the Storage computer (Refined Storage)
3. Drink from Grail
4. Behold!

#### Logs:
[crash-2021-01-16_07.40.20-client.txt](https://github.com/Extegral/Enigmatic-Legacy/files/5856921/crash-2021-01-16_07.40.20-client.txt) 

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
Looks like it's caused by Blazing Core effects, where it happens when core's ability forces some potion effect to expire prematurely.
