### ISSUE TITLE
[1.16.5] Enigmatic Amulet Vessel Voiding Items

### ISSUE THREAD

**Issue by oitsjustjose** [Extegral/Enigmatic-Legacy#146]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.10.3
 * Curios API: 4.0.4.0
 * Patchouli: 1.16.4-48
 * Forge: 36.0.13

#### Description of a Bug:
Upon death (with several items in my curios slots as well as hotbar), tools in the hotbar (tool items specifically, nothing else) don't get recovered by the soul vessel

I have tested in a standalone environment with just the required 3 mods and Forge and can repro this issue. Looking through the following code snippet: 

https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/c29e4d01f51af2250f0dbcf26e4a2b7378710a7f/src/main/java/com/integral/enigmaticlegacy/handlers/EnigmaticEventHandler.java#L1626-L1637

I don't see anything wrong here, so it might just be an issue with Forge's `evt.getDrops()`? I'm not sure what else could be the issue here. I have this weird hunch that it's hard-coded to expect 41 slots (36 inventory, 4 armor and 1 off-hand) and is capping the event to that for some reason, essentially forcing Curios' drops to effect this? I'm really not sure, and unfortunately I haven't had a lot of time lately to look into it :frowning:

#### How to Reproduce:
1. Have an inventory full of things, as well as all curios slots populated
2. Die
3. Be sad because your main tools are all gone now

#### Logs:
N/A

**Comment by Aizistral** [comment]
Could not reproduce this, in 1.16.5, using Forge 36.0.54 with EL 2.10.3. Specifically tried putting more than 41 item into my inventory, no problems appeared.
