### ISSUE TITLE
Experience related abilities don't work with /experience

### ISSUE THREAD

**Issue by Kisutora** [Extegral/Enigmatic-Legacy#149]
#### Versions:
 * Enigmatic Legacy: EnigmaticLegacy-2.10.3
 * Curios API: curios-forge-1.16.5-4.0.4.0
 * Patchouli: Patchouli-1.16.4-48
 * Forge: release 1.16.5-forge-36.0.15

No other mods installed.

#### Description of a Bug:
Experience related abilities don't work with experience added through the `/experience` command, such as Gift of the Heavens, Grace of the Creator, Scroll of Ageless Wisdom and Will of the Ocean.

Naturally acquired experience works fine, but if you have used the `/experience` command the abilities will only use the naturally acquired portion.

#### How to Reproduce:
1. Add any amount of experience with the `/experience` command.
2. Try to use an ability that uses experience.
3. *Behold!*

**Comment by Aizistral** [comment]
That's pretty weird. I've done all my tests with those items specifically with the help of `/experience` command, though it was quite some time ago. Perhaps 1.16.5 brought some changes that lead to this. Anyways, I will address this as soon as I find some time to work on the mod again.
