### ISSUE TITLE
Enigmatic amulet respawns every time someone logs into the server

### ISSUE THREAD

**Issue by alpharou** [Extegral/Enigmatic-Legacy#155]
enigmatic legacy 2.10.3
forge 36.0.43

Equipping it into a curios slot:
![image](https://user-images.githubusercontent.com/8113318/110557545-14fe4e80-8141-11eb-9b80-2e3ea521a91d.png)

Logging back in, it's also in inventory (the curios one dissapears when you try to take it):
![image](https://user-images.githubusercontent.com/8113318/110557677-5db60780-8141-11eb-8d7a-b0fd8cdcb44a.png)

**Comment by Aizistral** [comment]
Any submitted bug reports that disregard bug report template will not be reviewed. Please create another issue, following the template and properly filling in all requested data.
