### ISSUE TITLE
Unholy Stone issues

### ISSUE THREAD

**Issue by Aizistral** [Extegral/Enigmatic-Legacy#157]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.10.3
 * Curios API: _Irrelevant_
 * Patchouli: _Irrelevant_
 * Forge: _Unknown_

#### Description of a Bug:
Supposedly, for some arcane the Unholy Stone doesn't work any longer in latest versions of the mod... like, at all. Needs fixing if confirmed.

#### How to Reproduce:
1. Just use the stone lol

#### Logs:
Crash Log: _None_

**Comment by Aizistral** [comment]
Didn't confirm.

**Comment by Aizistral** [comment]
Did confirm. Does only happen if `keepInventory` is off.

**Comment by Korota-21** [comment]
> Did confirm. Does only happen if `keepInventory` is off.

it happens ether its true or false
