### ISSUE TITLE
[1.16.4] Duplicated blocks with acc that give Fortune level with other mods enchantment

### ISSUE THREAD

**Issue by mikado0605** [Extegral/Enigmatic-Legacy#163]
Versions:
- Minecraft 1.16.4
- EnigmaticLegacy-2.11.1
- Curios API: 4.0.4.0
- Patchouli: 50.0.0
- wonderful-enchantments-1.16.4-1.1.2

Description of a Bug:
- So, when i use seven cursed ring that give fortune level , somehow it can duplicated any box that i break using pickaxe with telekinesis enchantment from Wonderful Enchantments Mod , i think it perform to other tools too that can be enchanted with telekinesis such axe and shovel
- Telekinesis enchantment is enchantment that adds the item directly to the inventory if possible when destroying blocks. in this case , i get both blocks to my inventory and dropped on the floor

How to Reproduce:
- Equip seven crused ring
- Break blocks (i test it on diamond block) using pickaxe with telekinesis enchantment from Wonderful Enchantments mod
- diamond block that you break should enter your inventory immidietly , but if u use seven cursed ring it will drop on the floor and still get it on inventory

Logs:
Crash Log: N/A.

**Comment by Aizistral** [comment]
Report this to maintainers of Wonderful Enchantments. The implementation Enigmatic Legacy uses to add Fortune levels with some accessories is not independent and does reside in Curios API, I cannot alter it directly anyways.
