### ISSUE TITLE
Dark Scroll/Amulet/Spellstone of Ender Nature (or smt)

### ISSUE THREAD

**Issue by Tortyash** [Extegral/Enigmatic-Legacy#164]
RotSC makes enderman constantly angry at you, what makes exploring end near impossible. Pumpkin, potion of invisivility, (also End Veil and Enderite Armor) doesn't help.
Solution is counterpart to piglin's Pact of Infinite Avarice, that allows to neglate this curse, with some vulnerabilities like damage in water or random teleport if attacked, etc.

**Comment by Aizistral** [comment]
The Burden of Desolation now solves the problem of Endermen, even if not by re-neutralizing them as some expected.
