### ISSUE TITLE
Animal Companionship glitch

### ISSUE THREAD

**Issue by Tortyash** [Extegral/Enigmatic-Legacy#165]
#### Versions:
 * Enigmatic Legacy: 2.11.2
 * Curios API: 1.16.5-4.0.4.0
 * Patchouli: 1.16.4-50
 * Forge: 36.1.0
 * Environmental: 1.16.5-1.0.0
 * Alex's Mobs: 1.7.1

#### Description of a Bug:
I've noticed that Guide to Animal Companionship makes modded animals invulnerable to damage, but RotSC still makes them hostile, so they attack you and you can't fight back.

Аnimals seen in this behavior: Yak (from Environmental), Bear (from Alex's Mobs).

#### How to Reproduce:
1. Have some other mod which adds neutral animals;
2. Have Guide to Animal Companionship, as well as Ring of the Seven Curses equipped;
3. Encouter abovementioned neutral animals;
4. Suffer.

#### Logs:
_Irrelevant._

**Comment by Aizistral** [comment]
I am afraid this cannot be fixed without mod-specific integration on Enigmatic Legacy's side or without some kind of config option which would allow to blacklist any neutral mob from being affected by RotSC. Second way would allow more flexibility and I thus find it preferrable, but it might be a while until I get to implement it.

**Comment by alpharou** [comment]
Animal companionship could let you hit animal that were once neutral, but have aggro on you.

 Maybe disable the effect by shift + hitting the animal.
