### ISSUE TITLE
Full Spanish translation

### ISSUE THREAD

**Issue by alpharou** [Extegral/Enigmatic-Legacy#166]
Would the devs be interested in a Spanish translation?

I am spaniard and thus think I could do a really nice job at translating. Even though I don't have any experience with java/forge/building from source process, I really like this project and would like to add to it.

I'm assuming Enigmatic is capable of a full literal change, which may very well not be the case.

If the devs add new features and need to retrofit to Spanish, I will also be up for it.

**Comment by Aizistral** [comment]
Great. Localization files reside here: https://github.com/Aizistral-Studios/Enigmatic-Legacy/tree/1.16.X/src/main/resources/assets/enigmaticlegacy/lang
Each files contain multiple translation keys and language-specific localizations for them. A small example from the actual `en_us.lang` file:

```
"item.enigmaticlegacy.enigmatic_item": "Heart of Creation",
"item.enigmaticlegacy.magnet_ring": "Magnetic Ring",
"item.enigmaticlegacy.extradimensional_eye": "Extradimensional Eye"
```

`item.enigmaticlegacy.enigmatic_item` and those similar - are translation keys that need not to be altered. Right next to them are localized names, alike `"Heart of Creation"` and `"Magnetic Ring"`, that are to be translated. You will need to copy the original localization, and rename it from `en_us.json` to locale you're making translation for (for Spanish it should be `es_es.json`, I assume). From here you can translate all localized names.

I won't go into detail on setting up the workspace with mod and launching a client, the process is basically identical to setting up clean workspace with example mod from default Forge distribution, this repository contains everything required for that. May Google aid you in figuring this part out.

Once you have your translation complete and tested in-game, you can submit it via pull request.

Ask any questions if you happen to have any. Looking forward to see your works.

**Comment by alpharou** [comment]
I've imported a zip at time of: https://github.com/Aizistral-Studios/Enigmatic-Legacy/commit/bd3d21626d0397f07f3b743f5393a478b3f3f3ea as an exiting gradle project into eclipse.

I think I managed to build it, since the build/reobfJar/output.jar seems to load fine into a fresh forge installation.

For the time being I'll transfer the jar by hand, but, is there an easy way I could build and launch a client within eclipse?

**Comment by Aizistral** [comment]
Yes, among other gradle commands ForgeGradle plugin adds, you can use `gradlew runClient` in order to launch Minecraft client instance with code and resources freshly compiled and copied from main source set. I would advise you do so from command line rather than your workspace (you probably don't need workspace at all for what you're attempting). Also, I have this little thingy in my setup: https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/1.16.X/deps/BuildResourceUpdater-1.0.jar

If it works correctly, you should be able to test changes to your localization without need to re-launch client every time, just have it launhed already, save the file and do F3+T in-game to force MC to reload it's resources.

**Comment by Aizistral** [comment]
Any progress?

**Comment by alpharou** [comment]
Yes. All items and advancements are done, currently onto tooltips. Those are proving challenging because english/spanish syntax is not that similar, and as usefull it could be, is not possible to transfer print identifiers (+%1$s) between lines.

The most time consuming part will be the guide text for sure, so this will take a while.

**Comment by alpharou** [comment]
I think I'll take a break from translating until I get the wheels turning again. 

If anyone is up to it mention me on this issue and I'll provide the work in progress files.

@Aizistral Are you ok with it? This issue can be closed for the time being.

**Comment by Aizistral** [comment]
As you wish.
