### ISSUE TITLE
1.16.5 How disabled challenge when player first login in world

### ISSUE THREAD

**Issue by ghost** [Extegral/Enigmatic-Legacy#167]
Hi, cant find option to disable this in mod config. Mod version EnigmaticLegacy-2.11.2.jar

**Comment by Aizistral** [comment]
I do not understand what you mean by "How disabled challenge when player first login in world". Clarify your question.

**Comment by ghost** [comment]
I'm sorry, forget create screenshot. This challenge show when player first time login on server.
http://prntscr.com/10v6hc5

**Comment by Aizistral** [comment]
It is a notification dispatched by Patchouli. You can disable such notifications in Patchouli config.
