### ISSUE TITLE
[Suggestion] Heart of Creation shouldn't clear all potion effects

### ISSUE THREAD

**Issue by chimericdream** [Extegral/Enigmatic-Legacy#17]
I think the Heart of Creation item should only clear negative effects, such as poison, wither, etc. As it currently works, it simply clears all potion effects from the player, which negates things like night vision, haste, etc.

**Comment by Extegral** [comment]
I have concluded that there isn't much need for such change. Heart of Creation wasn't designed to be ultimate "carry all the time" gimmick, and is rather a situational tool that I so far found convenient in it's current implementation.
