### ISSUE TITLE
I found a incompatibility(mining any coal gives coal)

### ISSUE THREAD

**Issue by LinJonKur** [Extegral/Enigmatic-Legacy#173]
Hi! I've posted here about 2 days ago about what I thought to be a bug. That is when I mine any ore with some fortune charm on, it would give me only coal. I discovered that it was caused by the mod "Ore Stone Variants". I thought I'd let you know, maybe you could specify on the curseforge page or I don't really know, thought it would be useful information.

**Comment by Aizistral** [comment]
Any submitted bug reports that disregard bug report template will not be reviewed. Please create another issue, following the template and properly filling in all requested data.
