### ISSUE TITLE
Slayer Enchantment

### ISSUE THREAD

**Issue by LinJonKur** [Extegral/Enigmatic-Legacy#174]
Are the Slayer and Sharpness enchantment exclusive(can't have both)? If yes, can I change that?

**Comment by Aizistral** [comment]
Yes, they are, since Slayer is essentially just an unnerfed Sharpness, with rather minor restriction on entity types it is effective against. This currently cannot be altered and I have no plans to add such options, for same reasons why we can't have two sharpnesses on one sword.
