### ISSUE TITLE
Cursed Items are Unequipping upon reload/reconnect

### ISSUE THREAD

**Issue by Jusey1** [Extegral/Enigmatic-Legacy#175]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.2
 * Curios API: 4.0.5.0
 * Patchouli: 50.0
 * Forge: 36.1.0

#### Description of a Bug:
So, for a while now. I thought this was a mod-conflict issue only from mods over at Abnormals but I recently decided to test out the curse items specifically as they were the only ones being removed from their respective curios slots... I had only just Enigmatic Legacy and it's requirements installed, and found it is indeed a bug with the mod directly, which makes this separate from the other known similar bug (which has been fixed on the Abnormal side's devbuild).

Note: This bug only happens on the cursed items that requires the Ring of Seven Curses. Not the Ring itself.

#### How to Reproduce:
1. Load a save, equip ROSC
2. Equip a cursed item (like scroll of a thousand curses).
3. Leave, and reload the same save.
4. Watch as the cursed items are unequipped.

#### Logs:

Crash Log: N/A.

**Comment by Aizistral** [comment]
I guess this will be resolved as soon as my suggestion on Curios is implemented: https://github.com/TheIllusiveC4/Curios/issues/124

**Comment by Jusey1** [comment]
Awesome!~ Thanks you so much for bringing this to C4's attention then. Didn't even knew it was more of a Curios problem.

**Comment by milkev** [comment]
my (vanilla) elytra is being ejected from my back slot alongside the cursed baubles. is this related?

**Comment by Aizistral** [comment]
Should be fixed as of Curios update 4.0.5.1.

**Comment by milkev** [comment]
can confirm the vanilla elytra is no longer ejected as well, wooo fixes
