### ISSUE TITLE
Curios Bauble Ejection

### ISSUE THREAD

**Issue by viiizee** [Extegral/Enigmatic-Legacy#176]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.2
 * Curios API: 4.0.5.0
 * Patchouli: 50
 * Forge: 1.16.5 - 36.1.2

#### Description of a Bug:
Upon rejoining a single-player world my Enigmatic Legacy baubles are found in my inventory and not in the Curios inventory; provided there is enough space in my inventory for them. If there isn't space in the inventory, then the items get deleted.

When you open your inventory for the first time upon rejoining, the bauble slots will show that the Enigmatic items are still in their respective Curios slots, while simultaneously being in your Vanilla inventory. When you try to click the items in the baubles slots they disappear, leaving only the "duplicated" items in the inventory. They're not really duplicated it just appears that way until you attempt to select them with the left mouse.

I've made sure to test this with no other mods installed.

#### How to Reproduce:
1. Join any world or server.
2. Place Enigmatic Legacy items into the respective Curios slots.
3. Leave the world or server and rejoin.
4. Behold!

**Comment by Aizistral** [comment]
I guess this will be resolved as soon as my suggestion on Curios is implemented: https://github.com/TheIllusiveC4/Curios/issues/124

**Comment by Aizistral** [comment]
Should be fixed as of Curios update 4.0.5.1.
