### ISSUE TITLE
charm of the treasure hunter incompatible with curio mod

### ISSUE THREAD

**Issue by kuba26038** [Extegral/Enigmatic-Legacy#179]
curio api is one of the required mods for the mod, but i think i stumbled upon an bug connected t it. the charm of the treasure hunter says that it's effect of night vision can be disabled by right clicking on it while it's in one's hand, but if you do that, curios will force the player to equip it instead. i'd suggest changing the keybind for that, or maybe giving us an option to change it in the controls menu.

**Comment by Aizistral** [comment]
Any submitted bug reports that disregard bug report template will not be reviewed. This time's a bit of an exception, since the bug is small and I was able to easily confirm it, but be aware for the future.

Shall be fixed as of 2.11.3.
