### ISSUE TITLE
[1.6.2] crashing dedicated server

### ISSUE THREAD

**Issue by kreezxil** [Extegral/Enigmatic-Legacy#18]
I honestly don't know what my players are doing to cause this crash. If what I present below can not help you to fix it, I will have to **sadly** remove the mod from my pack.

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.6.2
 * Curios API: 1.0.5.4
 * Forge: 28.1.96

#### Description of a Bug:
Server crash when players do I don't know what, they certainly aren't telling me what they are doing.

#### Logs:

Server Crash Log:
http://paste.ubuntu.com/p/fR8WfZCBjS/

**Comment by Extegral** [comment]
You have the same issue as in #15. I'll fix it in soon.
