### ISSUE TITLE
[Enhancement] Add neutral anger blacklist for Ring of the Seven Curses 

### ISSUE THREAD

**Issue by Ritzumi** [Extegral/Enigmatic-Legacy#180]
**Provide a detailed and clear description of feature or change that you want to offer.**
Allow neutral anger curse from ring of the seven curses to has blacklist for preventing specific mobs from being affected by it.

**Describe why you want this. If there's a reason.**
The ring of seven curses provides a really good challenges for daring players. While I personally fine with angered endermans and most vanilla things, some modded mobs feel a bit wrong, guard villagers, for example. Therefore, allowing blacklist would benefit users to customize their experiences and maybe even further for modpack compilers.

**Comment by drakray** [comment]
Will this feature be added for 1.16.5?
I started a Hardcore game with the RotSC, and was killed within the 3 first minutes by GuardVillagers lol (that'll teach me to enter a village without invitation, I didn't even get to the ExtraGolems protecting the place XD)

**Comment by LTCatt** [comment]
Also this effects Iron Golem...

**Comment by Aizistral** [comment]
Okay, I'll do it in final release for 1.16.

**Comment by Terra-B-Welch** [comment]
Hate to be a gravedigger, but I wonder how well this was implemented... I really hope it was improved upon in later versions because alas, it does not work in the 1.16.5 version...

I know I'm better off talking to a brick wall and I'm getting nowhere with this, but in my denial I just hope to somehow get the config to work and actually make villager guards and iron golems not hate ringbearers regardless of config...

**Comment by drakray** [comment]
> 

Supposed to have been implemented in https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy/files/3608374

**Comment by drakray** [comment]
> Hate to be a gravedigger, but I wonder how well this was implemented... I really hope it was improved upon in later versions because alas, it does not work in the 1.16.5 version...
> 
> I know I'm better off talking to a brick wall and I'm getting nowhere with this, but in my denial I just hope to somehow get the config to work and actually make villager guards and iron golems not hate ringbearers regardless of config...

Supposed to have been implemented in [2.11.11](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy/files/3608374), second to last version for 1.16.5 (last is [2.11.12](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy/files/3758580))

**Comment by Aizistral** [comment]
@Terra-B-Welch if you have trouble figuring out list syntax - join my Discord server and ping me in **#help-and-questions**.
