### ISSUE TITLE
Config Option to disable Ring of Ender while wearing the Ring of the Seven Curses?

### ISSUE THREAD

**Issue by XAURAVUS** [Extegral/Enigmatic-Legacy#181]
I'd like to remove the option to use the built-in ender chest when wearing the Ring of the Seven Curses. Is this possible? If so, I would _love_ it - I want to make my mod-pack as difficult as possible lol. Thank you for your time.

**Comment by Aizistral** [comment]
Not possible as of yet. If you disable this ability, all of a sudden the ring will have six blessings instead of claimed seven. How are we gonna handle that?
