### ISSUE TITLE
Durability mechanism required.

### ISSUE THREAD

**Issue by rtxyd** [Extegral/Enigmatic-Legacy#185]
**Provide a detailed and clear description of feature or change that you want to offer.**
If the baubles get a durability attribute and durability consuming mechanism when player benefit from the them or triger the feature of them, it could be more balanced. And if it's possible, I hope all the items which have special fetures like baubles or "animal guild", "hunter guide", could get a durability system when player triger the features. 
And It's better that the durability could be turned on/off in config.
**Describe why you want this. If there's a reason.**
I am making my modpack of vanilla-like adventure and the balance system could be bad if there is a powerful gear which is able to permanantly work. However, I like those features, so I suggest this to you.

**Comment by Aizistral** [comment]
I'm generally not a big fan of limited-durability-accessories, it's more of an Artifacts thing. The mod is already designed to fit vanilla balance, and if you feel otherwise - there exist many other tools that you can utilize, be it tweaking item stats in config, harder recipies, greater progression requirements, or... whatever, you name it.

No final word on the matter though, I shall consider the possibility again whenever I'm back to active mod development.

**Comment by rtxyd** [comment]
Actually, my purpose is making the adventure continue after we finally get many powerfull stuffs. Because one day they will run out of durability, it also makes those items more treasurable. 
I agree that you has already considered many points of balance, this shows in conig. It's balanced enough somehow. First time I saw the whole config, I was agonize over wether I should post this suggest to you. And I saw words at the head of config, this made me decided to tell you.

No matter finally there will or not be a durability system, it's a good mod already.

**Comment by Aizistral** [comment]
After long, thorough consideration I have concluded that implementing such system would indeed be unviable as an optional thing in config. It might make sense to review some of the items currently present in the mod and make their durability limited, but it would then be limited by default with an option to make it infinite, not the other way around. Some more interesting approaches could be like the one outlined in #252, which I will consider in time.
