### ISSUE TITLE
"Enigmatic Package/Parcel/Box/lockbox"

### ISSUE THREAD

**Issue by Darkmega18** [Extegral/Enigmatic-Legacy#186]
_**Provide a detailed and clear description of feature or change that you want to offer.**_

A small package with maybe a few different nbt-able looks that when rightclicked it is opened and produces the signed enigmatic amulet which pops out infront of you and floats there at head height for you to collect glimmering slightly with little particle effects for a short time. 

Particle wise for the item, think thaumcraft thaumonomicon spawning effect back in the thaumcraft days where you'd transform a bookshelf and they'd turn into a book.

As a bonus so it has other uses the box and the resulting animation of the item popping out of the package and floating infront of you magically could be used as a cool way to produce the randomly generated item from the chests if made with nbt containing a loot table or such. If not given nbt or anything special in it, it'll just produce the amulet.

and further, the packages could be saved instead if you don't want to open them then be gifted or traded away to players or potentially to a villager or treasure hunter quest giver sort like a form of enigmatic loot bag of some kind for a bundle of resources perhaps. (or modpack makers could achieve that themselves if they desire using some other mod mechanics to produce those)

_**Describe why you want this. If there's a reason.**_

The reason I want it however is that the enigmatic amulet apparently is meant to appear in ones inventory at the start (or so I'm reading) and is a cool starting bonus and I honestly like the lore.
However, in my packs I often use custom starting gear which at the start of the world clears your inventory and replaces it with a player set collection of items locked in using a command. 
I usually set it up to provide some simple tools, utilities, documentation books and other things and it will usually contain anything the player should naturally spawn with that I think should remain, like doggy talents emblem and such.
However because of this I don't get an enigmatic necklace with a name cause the very first inventory on spawn is replaced within a couple of ticks of joining for the custom starting gear set up, and if I put it in custom starting gear anyone who plays will end up with either an uninscribed necklace or one that I've already set up with a name or my own. :< so with this item, you get a sorta alternative way to produce the amulet, by being given the package and then opening it at the start of the game which can be attached to custom starting gear.

**Comment by Darkmega18** [comment]
alternatively, enigmatic amulet could be set up to gain it's name when spawned from creative just not gain it until it hits the hotbar. that way a creative one could be taken from jei into inventory where it won't do it's tick to get engraved and I could just put it in a bag or something for the spawning player to take out of the bag and look at or something.

**Comment by 4AC11** [comment]
maybe this could work similarly to Botania's Dice of Fate items, where as soon as an unbound item enters a players inventory it becomes bound. i'm not sure how difficult that would be to do with the randomized aspect of the amulet though (maybe there could exist a gray amulet that can only be obtained via commands, similar to having a blank spawn egg or uncraftable potion? perhaps this item could automatically randomize itself and become assigned to the player upon entering their inventory)

**Comment by Darkmega18** [comment]
@4AC11 This was an old idea because I had that custom starter gear thing that was ruining the stuff I was meant to spawn with. 

but with the addition of actual compatibility with that so that it doesn't obliterate the items unless I put them in a blacklist that isn't very clear or obvious (which at the time, I did discover it eventually) this isn't all that useful anymore. 

unless, yeah, aizistral wants do loot drops and adapt it to such a mechanic.

**Comment by Aizistral** [comment]
Consider that I rolled the dices to select two completely random features to be implemented in the last release for 1.16, and somehow this one ended up winning the odds. I've gone with a simpler way to make it, which is to just create a separate item transforming itself into bound Enigmatic Amulet as soon as it enters player's inventory, in the exact same way as granting an amulet at the start of the game works. All in all this should be a reasonable thing for modpack developers who might not want the amulet to be a starter item for whatever reason.
