### ISSUE TITLE
Scroll of Ageless Wisdom won't activate

### ISSUE THREAD

**Issue by Anuuviem** [Extegral/Enigmatic-Legacy#187]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.4
 * Curios API: 1.16.5-4.0.5.1
 * Patchouli: 1.16.4-51
 * Forge: 36.1.23

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. Install forge and req mods
2. acquire scroll of ageless wisdom
3. attempt to activate via shift+right click or keybind
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
I don't know what happened in your instance, but note that it's actually activated not by Shift+Right-Click, but by pressing Right-Click (or keybind) when _sneaking_.

**Comment by HeavyDeception** [comment]
I have this bug happening to me right now
