### ISSUE TITLE
Rings/Relics effect all people on the server not the individual user

### ISSUE THREAD

**Issue by Traverse-Joe** [Extegral/Enigmatic-Legacy#188]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:
 * Curios API: 1.16.5-4.0.5.1
 * Patchouli: 1.16.4-51
 * Forge:1.16.5-36.1.25

#### Description of a Bug:
I noticed that the rings/relics we used effected all the people on the server. 

#### How to Reproduce:
1. An example item is to have the magnetic ring equipped
2. Have another player nearby.
3. Have other player try to drop items and they items will go back to the player like they have the magnetic effect.
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
With magnetic ring this is an intended behavior (see #177 for reference).
What other items you suppose provide their effects to other players?

**Comment by Traverse-Joe** [comment]
it seems like the curse effect is causing other ppl to experience the issues. like being unable to deal damage to mobs hardly.

**Comment by Aizistral** [comment]
I've tested Ring of the Seven Curses and could not get it to affect other players without it in unintended ways.
