### ISSUE TITLE
Cursed Ring neutral aggravation bypasses invisibility inconsistently

### ISSUE THREAD

**Issue by Jackiecrazy** [Extegral/Enigmatic-Legacy#194]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.4
 * Curios API: 4.0.5.2
 * Patchouli: 53
 * Forge: 36.1.31

#### Description of a Bug:
Endermen, wolves, bees, Alex's bears, and any other mobs that would be aggravated by the cursed ring will continue to target an invisible player. That'd be fine as a mechanic, but hostile mobs aren't affected and will continue to stand around when an invisible cursed player is around them. That is, the aggravation test does not factor in `LivingEntity#getVisibilityMultiplier`.

#### How to Reproduce:
1. Drink an invisibility potion in survival and observe an enderman and a skeleton from 10 blocks away; neither will attack, as its detection range has been reduced to 4 blocks in this state.
2. Wear the cursed ring.
3. The enderman will begin to attack you regardless of whether you look at it, but the skeleton remains oblivious.

#### Logs:
No logs, just rather strange behavior.

**Comment by Aizistral** [comment]
Thanks for pointing out, I indeed should factor in that visibility multiplier thing.
