### ISSUE TITLE
 The enigmatic amulet doesn't return items when I approach it.

### ISSUE THREAD

**Issue by DFTOM** [Extegral/Enigmatic-Legacy#195]
#### Versions:
 * Enigmatic Legacy: 2.11.4.jar
 * Curios API: Curios-forge-1.16.5-4.0.5.2
 * Patchouli: Patchouli-1.16.4-50
 * Forge: Forge-1.16.5-36.1.0

#### Description of a Bug:
 The enigmatic amulet doesn't return items when I approach it.

#### Reproduce:
1. Can not receive items and soul from the enigmatic amulet.
2. Could just pass through it.
3. Wear Ring of the Seven curses.
4. Image: ![Screenshot (5)](https://user-images.githubusercontent.com/69234750/126013496-83ca4d23-8e4b-4785-b3a5-2c26c6235edf.png)
5. Behold!

#### Logs:
 No logs.

**Comment by Aizistral** [comment]
I could not reproduce this in my tests. It is known that only player who left the Soul Crystal or Extradimensional Vessel embedding such crystal can pick it back up, but in both cases owner is recognized by UUID. Unless your player ID changed (like you logged in from different account), I have no idea how that could have happened.
