### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by KamiSami** [Extegral/Enigmatic-Legacy#2]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: EnigmaticLegacy-1.1.0.jar
 * Curios API: curios-FORGE-1.14.4-0.24.jar
 * Forge: forge-28.0.93

#### Description of a Bug:
Server will not start with this and curios mod.

#### How to Reproduce:
1. Launch server with Enigmatic Legacy and Curios API mod
...
n. Behold!

#### Logs:

Crash Log: https://pastebin.com/sqCkqESY For the crash log, and https://pastebin.com/XhPLzvZv for the latest log

Also if im doing something wrong, please let me know, may help some others too if they read about of this issue

**Comment by Extegral** [comment]
It's been my mistake. I never actually tried to lauch a server with my mod, and it appears that a bunch of client-only fields and classes are attempted to be used on server side, which results in crash.

I will fix this until next update.

**Comment by BuilderDan** [comment]
Ran into the same issue, praying for a fix
