### ISSUE TITLE
onBlockDropsHarvest console spam

### ISSUE THREAD

**Issue by 88onme** [Extegral/Enigmatic-Legacy#20]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.6.2
 * Curios API: 1.0.6
 * Forge:  28.1.107

#### Description of a Bug:
Quarry from [Additional Enchanted Miner](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner) causes immense console spam with enigmatic. Since the quarry is mining blocks every second, there is a ton of console spam saying the HarvestDropsEvent was fired. Is this necessary to print? I assume it might be something for debugging you left in.

https://github.com/Extegral/Enigmatic-Legacy/blob/31e1c4f12de43e3d39e4e41ad77c117318d3aaf2/src/main/java/com/integral/enigmaticlegacy/handlers/EnigmaticEventHandler.java#L230-L236

**Comment by Extegral** [comment]
This even was never actually fired by Forge in it's previous versions. Glad to see they've fixed it.

I will remove that thing in next release.
