### ISSUE TITLE
[BUG] Ender chest button not moving when Quark oddities backpack equiped.

### ISSUE THREAD

**Issue by KKotik** [Extegral/Enigmatic-Legacy#201]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.4
 * Curios API:  4.0.5.2
 * Patchouli: 53.2
 * Forge: 36.2.4
 * Quark and Quark oddities: any.

#### Description of a Bug:
The button to not move, when I expand my inventory with quark's backpack.

#### How to Reproduce:
1. Equip ender ring or ring of the seven curses
2. Equip Quark's Oddities Backpack
3. Open inventory

#### Logs:
Do not actually need here.

![image](https://user-images.githubusercontent.com/45950781/133665089-b7d15075-8bf7-4b29-8f03-5ecd092f8f2f.png)
![image](https://user-images.githubusercontent.com/45950781/133665113-bbcc6c08-3632-4453-a8fa-af0123387170.png)

**Comment by Aizistral** [comment]
I wonder who had this ingenious idea of completely altering the layout of default player inventory. But I guess button should be fixeable if I just change the anchor point, so I'll adress this issue.
