### ISSUE TITLE
Better Minecraft Plus

### ISSUE THREAD

**Issue by DoomZealot** [Extegral/Enigmatic-Legacy#203]
Hello. I recently started the Better Minecraft Plus modpack with some friends. I had never played with Enigmatic Legacy before and I love it a lot. Upon researching online, which information is hard to find on many things on this mod, I found out you're supposed to spawn in with ring of seven curses and amulet?

None of us spawned with them so I was curious if this was intentional or not.

Thanks!

**Comment by Aizistral** [comment]
Your modpack might have them disabled in config. Check Accessibility Config in `enigmaticlegacy-common.omniconf` file in your config folder; if those two items are disabled there, modpack developer probably intended them to be unobtainable, or have some other modpack-specific way of obtaining.
