### ISSUE TITLE
Serious memory leak when re-entering a world

### ISSUE THREAD

**Issue by LTCatt** [Extegral/Enigmatic-Legacy#208]
#### Versions:
 * Enigmatic Legacy: 2.11.5
 * Curios API: 4.0.5.1
 * Patchouli: 53.2
 * Forge: 36.2.0

<br></br>

#### Description of a Bug:
Each time you quit to title and re-enter a world, the game's memory usage will increase. (if you install more mods, the increased memory usage will become even significantly larger)

<br></br>

#### How to Reproduce:
In addition to this Mod, I also installed Chunk Pregenerator. It provides a command "/pregen utils GC" which triggers Full GC, so I can get an accurate memory usage.

Enter the game for the first time, walk around a few times, and trigger Full GC. At this point, about 400M memory was used.

![image](https://user-images.githubusercontent.com/40348278/136987143-997aeaf4-cd9f-4f73-9781-09614f39ad88.png)

Quit to title and re-enter the game. Repeat 4 times. At this point, about 650M of memory was used.

![image](https://user-images.githubusercontent.com/40348278/136987513-a7a83046-04b8-4f1e-9ea8-74d75721130d.png)

If Enigmatic Legacy is disabled and only Curios, Patchouli, and Chunk Pregenerator are installed, the memory usage is 420M after repeating these steps, which is almost no increase from the beginning.

<br></br>

In my modpack with 80 mods installed, each re-enter adds **MORE THAN 300M** memory usage.

When I changed map a few times at one point, I saw the game's memory usage increase from 1.2G to **OVER 3G**, which was horrible... So I went through all the mods using dichotomy and finally found that when this mod was disabled (other 79 mods are still enabled), this bug disappeared...

**Comment by Aizistral** [comment]
One day I'm just going to go and live on a farm and keep chickens.

**Comment by DonorKrovi** [comment]
And when will it be fixed? I have 1 this mod already uses 6 GB of RAM lmao

**Comment by Aizistral** [comment]
> And when will it be fixed? I have 1 this mod already uses 6 GB of RAM lmao

As soon as I figure out what and where causes the issue.

**Comment by Aizistral** [comment]
After hours of debugging I think I finally identified the cause. It would appear to be in multiple maps and multimaps which hold reference to outdated player objects, which in turn reference an entire christmas tree of other data; as a result they prevent garbage collector from gently touching any of that. Fix might take some time due to multiple sources behind this issue, but it is doable.

**Comment by Aizistral** [comment]
I suppose I fixed this, but it would be cool if someone could test new update to confirm it is indeed fixed.
