### ISSUE TITLE
Unique Drops for Ring of the Seven Curses cannot be cancelled

### ISSUE THREAD

**Issue by LTCatt** [Extegral/Enigmatic-Legacy#210]
Emeralds and some other items were disabled in my modpack, but I found there was absolutely no way to cancel these drops for Ring of the Seven Curses.
If possible, can you provide a way to modify these drops?

https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/4796939b93ce61a5caa76752cc217645a966f442/src/main/java/com/integral/enigmaticlegacy/handlers/EnigmaticEventHandler.java

**Comment by Aizistral** [comment]
I implemented two config options to address this, one which allows to adjust chance of emerald dropping from any mob when having Pact of Infinite Avarice equipped, and another one that allows to disable all other special drops. I am aware that this is not a perfect solution, but hope that it will do for the time.
