### ISSUE TITLE
Hotkey for the magnet rings.

### ISSUE THREAD

**Issue by HeavyDeception** [Extegral/Enigmatic-Legacy#213]
**Provide a detailed and clear description of feature or change that you want to offer.**
A way to turn off and on the magnet ring and Dislocation Ring with a hotkey.

**Describe why you want this. If there's a reason.**
Accessibility and more control for the rings say you want to drop your inventory full of bread to feed you villagers.

**Comment by Aizistral** [comment]
This basically mirrors what was already mentioned in #49.
