### ISSUE TITLE
Piercing Enchantment + Angel's Blessing Reflect

### ISSUE THREAD

**Issue by SelkeGore** [Extegral/Enigmatic-Legacy#219]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.6
 * Curios API: 4.0.5.1
 * Patchouli: 51
 * Forge: 36.2.0

#### Description of a Bug:
Projectiles from Piercing-enchanted crossbows cause the game to stall and eventually crash when Angel's Blessing deflect chance is set to 100% and it tries to deflect such projectile. This bug seems to occur on all version of Enigmatic Legacy across 1.16, and probably earlier ones too.

#### How to Reproduce:
1. Set Angel's Blessing to reflect 100% of the time
2. Have a pillager shoot an arrow with a piercing crossbow
3. Voila! Crash. 

#### Logs:
_Irrelevant._

---

Currently plaguing my server as I can't just disable a vanilla enchantment so I'd appreciate a fix.

**Comment by Aizistral** [comment]
Be a lot cooler if you attached your crashlog. I know I can reproduce this but that would save me some time.
Also be cool if you specified versions anyways, besides all else this is requested for archival purposes (as much as crashlogs are).

At any rate bother not, I already did everything myself.
