### ISSUE TITLE
Pearl of the Void & Forbidden Fruit 

### ISSUE THREAD

**Issue by SonRaon** [Extegral/Enigmatic-Legacy#220]
Hello @Aizistral !! 
I have downloaded your hidden gem of a mod called Enigmatic Legacy and I have a question regarding the healing reduction of the Pearl of the Void spellstone and the Forbidden Fruit once the former is equipped or the latter is consumed.

 Is the healing reduction only for the player's natural regeneration factor (Basically the small regen factor that a player has with full hunger bar)  or is it for every health regain type that's added either in normal minecraft (via golden apples or the potions of Regeneration and Healing) or through mods (Lifesteal and such)?

 I'm asking since I was planning on adding the mod into a private modpack of mine and I would like to know if there's a way to play around the healing reduction without messing up with the other health gain properties of my modpack.

**Comment by Aizistral** [comment]
Technically, reduction applies in every healing event when 1.0 or less health points are restored at a time. Thus, it affects regeneration potions and whatnot just as much as natural regeneration, but instant health potions for instance are unaffected.
