### ISSUE TITLE
Scroll of Ageless Wisdom Unlimited XP (Mod Conflict)

### ISSUE THREAD

**Issue by HeavyDeception** [Extegral/Enigmatic-Legacy#223]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.6
 * Curios API: 4.0.6.1
 * Patchouli: 53.2
 * Forge: 36.2.9

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. install [PlayerEX](https://www.curseforge.com/minecraft/mc-mods/playerex) With EL.
2. Give Scroll to self and Turn on.
3. Place in the scroll slot and
4. Behold!

#### Logs:
No Crash logs are made.

Remember [this guy](https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues/212#issuecomment-973156506) wish he would have told me what pack he had installed I would have gotten to this so much sooner lol.

**Comment by Aizistral** [comment]
Uhmmm... But how do you install PlayerEx with Enigmatic Legacy when PlayerEx is Fabric-only?

**Comment by HeavyDeception** [comment]
The one I sent you is for forge.

**Comment by HeavyDeception** [comment]
I just looked at that link and tho it say its for fabric you can install it and it works odd that it let's you.  As of the 1.1.8 update. And that's the one I have installed.

**Comment by Aizistral** [comment]
Ah, so that's what happened... https://github.com/CleverNucleus/PlayerEx/releases/tag/v2.0.1
I wonder why the project page states it as if Forge was never supported in the first place.

**Comment by Aizistral** [comment]
Alright, I will investigate this with PlayerEx 1.1.8-1.16.5 later. However, since mod author apparently dropped support for Forge altogether - we cannot expect collaboration on this matter, and thus it's possible that I will not be able to address this issue on my side.

**Comment by Aizistral** [comment]
This issue falls entirely on the side of my mod. Still thinking on how to fix it, but fix it I shall.

**Comment by HeavyDeception** [comment]
It's such an odd bug.

**Comment by Aizistral** [comment]
Should be fixed in 2.11.9.
