### ISSUE TITLE
Mod fails to load on server (again)

### ISSUE THREAD

**Issue by mosharky** [Extegral/Enigmatic-Legacy#227]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.8
 * Curios API: 4.0.6.8
 * Patchouli: 53.2
 * Forge: 36.2.22

#### Description of a Bug:
`Failed to create mod instance. ModID: enigmaticlegacy, class com.integral.enigmaticlegacy.EnigmaticLegacy`. I don't understand much beyond that.

#### How to Reproduce:
1. Attempt to start server
2. Experience crash

#### Logs:

Crash Log: https://pastebin.com/JkuaPNpd
latest.log: https://pastebin.com/v9sP4mwU

**Comment by Aizistral** [comment]
Both your crash log and latest.log clearly indicate you are using 2.11.7. You sure you did update?

**Comment by mosharky** [comment]
oh my bad, the servers auto-installing off a previous version of the modpack. Hard to explain but this is a problem on my end. Cheers
