### ISSUE TITLE
Server freezing

### ISSUE THREAD

**Issue by bigenergy** [Extegral/Enigmatic-Legacy#230]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.9
 * Curios API: 4.0.6.5
 * Patchouli: 53.2
 * Forge: 1.16.5-36.2.22

#### Description of a Bug:
The server started to freeze after updating the mod to the latest version

#### How to Reproduce:
I can't figure out how to reproduce this :(

https://gist.github.com/bigenergy/b5cdeb53c198278c6686f9360a81c38d

**Comment by XionioXMaster** [comment]
same

**Comment by Aizistral** [comment]
While I was not exactly able to reproduce this issue, I suppose changes in the upcoming update should fix this. Be kind of you to check whenever you can and report back.
