### ISSUE TITLE
tome of hungering knowledge don't work on server

### ISSUE THREAD

**Issue by Pachoto** [Extegral/Enigmatic-Legacy#231]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.9
 * Curios API: 1.16.5-4.0.5.3
 * Patchouli: 1.16.4-53.2
 * Forge: 36.2.22
 * (if need) Server core: Mohist 1.16.5 (908)

#### Description of a Bug:
tome of hungering knowledge don't work on server, when i try to combine tome with any other item with enchantment, item just back to inventory and created book just disappeared when i close inventory or try to get she

#### How to Reproduce:
1. Start forge minecraft server with mod
2. Get any item with enchantment
3. Combine with tome of hungering knowledge and try to get him from craftable 
4. Behold!

#### Logs:
<html>
<body>

[16:09:05] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
--
315 | [16:09:05] [Server thread/WARN] [/]: java.lang.IllegalArgumentException: Recipe must have non-AIR result.
316 | [16:09:05] [Server thread/WARN] [/]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
317 | [16:09:05] [Server thread/WARN] [/]: at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:47)
318 | [16:09:05] [Server thread/WARN] [/]: at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:18)
319 | [16:09:05] [Server thread/WARN] [/]: at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:22)
320 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.item.crafting.ShapelessRecipe.toBukkitRecipe(ShapelessRecipe.java:38)
321 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.item.crafting.ShapelessRecipe.toBukkitRecipe(ShapelessRecipe.java:19)
322 | [16:09:05] [Server thread/WARN] [/]: at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15)
323 | [16:09:05] [Server thread/WARN] [/]: at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:123)
324 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2293)
325 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34)
326 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12)
327 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
328 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
329 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
330 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
331 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
332 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
333 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
334 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
335 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
336 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
337 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905)
338 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825)
339 | [16:09:05] [Server thread/WARN] [/]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
340 | [16:09:05] [Server thread/WARN] [/]: at java.base/java.lang.Thread.run(Thread.java:829)

</body>
</html>

**Comment by Aizistral** [comment]
Seems to be a Bukkit issue first and foremost, but upcoming update includes changes which should alleviate this.

**Comment by Pachoto** [comment]
Many thanks! Now it works well
