### ISSUE TITLE
Disabling Starter Ring

### ISSUE THREAD

**Issue by RynShirayuki** [Extegral/Enigmatic-Legacy#232]
Hello I am making a mod pack and I would like to put the ring behind FTB Quests (Which I know how to do), but I cannot seem to find where you can disable the ring being given on first login.

**Comment by Aizistral** [comment]
Right there:
![image](https://user-images.githubusercontent.com/47505981/148692935-ab210134-af52-415e-ae57-62851e67af1b.png)
Before you ask - yes, this option does not "delete" the item, just makes it so that it's not given to players when they spawn.
