### ISSUE TITLE
Game crashes with Apotheosis mod

### ISSUE THREAD

**Issue by Niketats** [Extegral/Enigmatic-Legacy#238]
Enigmatic Legacy: 2.11.10
 Curios API: 4.0.5.3
 Forge: 3.2.20
 Apotheosis: 4.8.4

Description of a Bug:
Game crashes with this error, onle with Enigmatic Legacy 2.11.10, with 2.11.9 everything ok

How to Reproduce:
1. install Enigmatic Legacy 2.11.10 and Apotheosis
2. Behold!

Crash Log: https://pastebin.com/1LsfXjqT

**Comment by 4AC11** [comment]
I'm having the same issue! It just started today when I updated Enigmatic Legacy. D: Hope a fix can be implemented soon, for now I'll just have to play on the last version.

**Comment by Aizistral** [comment]
Patch will be out today.
