### ISSUE TITLE
[BUG] Cannot enter world

### ISSUE THREAD

**Issue by LunarFactory** [Extegral/Enigmatic-Legacy#239]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.10
 * Curios API: 4.0.6.8
 * Patchouli: 53.2
 * Forge: 36.2.22

#### Description of a Bug:
Trying to load into the world with Enigmatic Legacy installed causes datapack loading error to be shown.

#### How to Reproduce:
1. Install Enigmatic Legacy;
2. Launch;
3. Enter the world;
4. Behold!

#### Logs:
Here: [Click](https://www.toptal.com/developers/hastebin/donofohopo.rb)

**Comment by Aizistral** [comment]
That's... not how you're supposed to attach logs, but fine, I'll let it slip this once.

**Comment by LunarFactory** [comment]
> That's... not how you're supposed to attach logs, but fine, I'll let it slip this once.

Sorry :( But there was so many trash logs. and it doesnt generated crash logs. anyway, Thanks a lot!
