### ISSUE TITLE
Axe of Executioner do not work in server

### ISSUE THREAD

**Issue by LyricaPrismriver** [Extegral/Enigmatic-Legacy#24]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.6.2
 * Curios API: 1.0.6
 * Forge: 28.1.109

#### Description of a Bug:
Axe of Executioner do not work in forge server.

#### How to Reproduce:
1. start a forge server
2. use Axe of Executioner to slain a wither skeleton or other monster
3. it's not work! the behead chance still very low

#### Logs:
Crash Log: no error log

**Comment by Extegral** [comment]
I have tested this on Forge 28.1.115 and wasn't able to reproduce the issue.

Try to increase the base beheading chance to some high value in config and use it on one of mobs that have heads but do not drop them by default (like Zombie). Perhaps you're just never lucky. Reply if it still won't work.
