### ISSUE TITLE
[1.18.1] Soul Vessel does not actually generate if death occurred below Y0

### ISSUE THREAD

**Issue by Not-February** [Extegral/Enigmatic-Legacy#243]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.13.1
 * Curios API: 5.0.5.2
 * Patchouli: 1.18.1-64
 * Forge: 39.0.44

#### Description of a Bug:
The log says that it generates and lists the coordinates where it's meant to be, but upon going to the location of my death the vessel is nowhere to be found.

If I die in a cave above Y0 or on the surface this doesn't happen and the grave spawns from the amulet item as expected.

This is an issue because in 1.18+, the lower world height limit is -64, not 0. There are naturally generating caves and structures below Y0.

I have to wonder if this is an issue brought about by the kind of air that populates caves being changed, "cave air" and "void air" are apparently things according to the [Minecraft wiki](https://minecraft.fandom.com/wiki/Air) and I wouldn't be surprised if one of the two is being used for caves below Y0 now.

If the extradimensional vessel requires simply 'minecraft:air' to spawn and doesn't account for whichever is used in these caves, that would be my guess about why things could be going wrong.

#### How to Reproduce:
1. Equip Enigmatic Amulet
2. Die in some way while below Y0
3. Go back to where you died
4. Behold! No vessel and your stuff is gone forever.
5. Repeat steps 1-3 anywhere above Y0 and note that this does not happen.

#### Logs:

latest.log : https://gist.github.com/Febilian/ef6fb1400ebba64c633c22463870d83c

**Comment by Aizistral** [comment]
Oh god, I totally forgot about world height change. In the older versions it used to be so that if you die below Y=0 the vessel will actually spawn at around Y=0, X and Z coordinates staying the same; it was done to ensure player will still be able to get their items back even if they died deep within the Void. Could you confirm whether or not vessel appears at 0 level?

**Comment by Not-February** [comment]
Just tested again with a fresh test, it does indeed appear to generate at Y0! Better than losing stuff forever but still not ideal haha.

**Comment by Aizistral** [comment]
Gonna patch this today.
