### ISSUE TITLE
Toggle Magnet/Dislocation

### ISSUE THREAD

**Issue by TrueGuardian32** [Extegral/Enigmatic-Legacy#245]
**Provide a detailed and clear description of feature or change that you want to offer.**
I'd like the Magnet or Dislocation Ring to be togglable via keybinding it.
**Describe why you want this. If there's a reason.**
Several, and I mean several, mods require you to drop items inorder to do things like say, a ritual or something. In that case we would like the ability to turn it off temporarily without having to hold shift for the entirety of said thing. It can also pick up drops around the base that we might not want to get picked up at the time, say for example you go beside the chicken pen, suddenly you have EGG.

**Comment by SoulRacer65** [comment]
there is a setting in the config that allows you to invert the way the magnet rings work, which makes it so that you have to sneak in order to attract items to you

**Comment by ilyvion** [comment]
It'd still be nice to have a toggle though; something akin to the Thermal Series' shift+right-click to activate and deactivate an item. For instance, you can deactivate the flux capacitor before picking up a machine so it doesn't dump its charge into the machine.

**Comment by Aizistral** [comment]
I remeber someone long ago suggested to make it toggleable via some sort of special button in the inventory, which would appear if you have one of these rings equipped. Maybe that would be a better solution?

**Comment by TrueGuardian32** [comment]
If you could move the button? Yes.

**Comment by Khaeops** [comment]
The current placement of the button interferes with buttons from several other mods, such as Diet or portable crafting.

**Comment by Aizistral** [comment]
> The current placement of the button interferes with buttons from several other mods, such as Diet or portable crafting.

Look, there's only so much space in player's inventory. Wherever I place my buttons by default, they are bounds to interfere with something. You can head over to client config (`enigmaticlegacy-client.omniconf`) and adjust button positioning however you see fit using offsets, be it for personal use or for whole modpack. To make adjustment proccess simpler - config is reloaded dynamically upon saving, just reopen the inventory to see the results, no game restart required.

**Comment by Khaeops** [comment]
My bad I missed that option in the config. Thanks for clearing that up though!

**Comment by Aizistral** [comment]
You're welcome.
