### ISSUE TITLE
Config Option to disable Forbidden Fruit's debuffs on consumption

### ISSUE THREAD

**Issue by legitch** [Extegral/Enigmatic-Legacy#247]
**Provide a detailed and clear description of feature or change that you want to offer.**
See title. Just a config option within enigmaticlegacy-common that disables the debuffs gained from the Forbidden Fruit without disabling the item or its effects.

**Describe why you want this. If there's a reason.**
I feel that the debuffs only serve to kill unsuspecting players who don't know about the effects, which can be irritating in Hardcore mode, and for a modpack I'm making, I'd like players to be able to acquire this item before the Nether (aswell as before any healing potions are able to be crafted) and use it without dieing or being close to death's door.

**Comment by Aizistral** [comment]
I shall implement this as a multiplier for the length of all applied debuffs, which, if set to 0, will disable them entirely.
