### ISSUE TITLE
Console Spam with Industrial Foregoing

### ISSUE THREAD

**Issue by zedekblue** [Extegral/Enigmatic-Legacy#25]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.6.2
 * Curios API: FORGE-1.14.4-1.0.6
 * Forge: 14.4-28.1.109
 * Modpack: All The Mods 4 - v0.3.0 (With EL added)

#### Description of a Bug:
When Industrial Foregoing Gatherer collects anything, the server log is spammed with enigmatic legacy events for every block destroyed.
![0001](https://user-images.githubusercontent.com/17040113/72102895-46814d00-32e5-11ea-9b4c-8a93b5b230f3.png)
![0002](https://user-images.githubusercontent.com/17040113/72102902-484b1080-32e5-11ea-9291-a1352218b55b.png)

#### How to Reproduce:
1. Use a gatherer
2. Have it do the thing it does
3. Behold the spam

I can test this a bit more extensively without other mods in the pack if you have trouble reproducing or figuring out the cause of this one.

**Comment by Extegral** [comment]
This is the same issue as #20.
