### ISSUE TITLE
Crash on Startup: Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/model/Model

### ISSUE THREAD

**Issue by EchoWhiskeyZero** [Extegral/Enigmatic-Legacy#251]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: EnigmaticLegacy-2.13.2.jar
 * Curios API: curios-forge-1.18.1-5.0.5.2.jar
 * Patchouli:  Patchouli-1.18.1-64.jar
 * Forge: MinecraftForge v39.0.59

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. Install Forge server MinecraftForge v39.0.59 (I'm running on Ubuntu with Java17)
2. Start server (run.sh)
3. Server crashes on startup

#### Logs:

Crash Log: [Please use a paste site like [hastebin](https://hastebin.com/).](https://www.toptal.com/developers/hastebin/welolunufu.sql)

**Comment by Aizistral** [comment]
Looks like it's the same things as in #246. I'll be releasing 2.14.0 in, like, half an hour, should fix that.
