### ISSUE TITLE
【BUG】The CursedRing Will occupy 2 ring positions

### ISSUE THREAD

**Issue by blood789** [Extegral/Enigmatic-Legacy#256]
When i set this to true,
CursedRingUltraHardcode=true,
The CursedRing Will occupy 2 ring positions at survive mode when I first join the game.

AT this time, I set gamemode to creative, attempt to remove 2 CursedRing. There will only be 1 ring in the bag.

**Comment by blood789** [comment]
![2022-01-29_13 35 37](https://user-images.githubusercontent.com/70810047/151656757-3d8b5fd7-f744-4b04-8f82-380ccb1103bf.png)

**Comment by Aizistral** [comment]
Any submitted bug reports that disregard bug report template will not be reviewed. Please create another issue, following the template and properly filling in all requested data.
