### ISSUE TITLE
Follow particle settings with certain items

### ISSUE THREAD

**Issue by zedekblue** [Extegral/Enigmatic-Legacy#26]
Astral Breaker & Dislocation ring both produce massive amounts of particles, and currently produce the same amount of particles regardless of whether Video Settings are on All, Decreased, or Minimal.

My suggestion is simply to produce less particles if these settings are lowered.

For example:
Using veinminer on stone will easily break ~200 blocks per use. Combine that with any instamining pickaxe, let alone one with an AOE that works with veinminer, and you're breaking a few thousand blocks every couple seconds. Without a dislocation ring, I can handle this just fine. Using a botania ring of magnetisation (no particles) allows me to do this. However with a Dislocation ring, I am producing not only a few thousand block entities, but several thousand particles as well. I get considerable fps lag using it.
Rather than change how the ring works, a simple workaround is to simply lower graphics settings. Unfortunately, this currently does not effect Enigmatic Legacy items in any way.

**Comment by Extegral** [comment]
Sounds reasonable. Will implement.
