### ISSUE TITLE
Option to configure the Guide to Animal Companionship's interaction with the Second Curse

### ISSUE THREAD

**Issue by Not-February** [Extegral/Enigmatic-Legacy#260]
**Provide a detailed and clear description of feature or change that you want to offer.**

As a modpack maker, I think it'd be nice if it were possible to configure neutral animals that are rendered neutral towards a player wearing the Ring of Seven Curses but *only* if they're carrying the Guide to Animal Companionship, like is the case with bees and wolves by default.

Currently there is a list to define creatures which aren't affected by the Second Curse at all, and that technically *works* and I'm glad it's an option, but I'd still really like the option to still allow the second curse to be a threat without completely negating the player's ability to interact with modded neutral animals.

Ideally mobs which are defined in this way would be dynamically shown in-game somehow.

I do worry about the tooltip getting too large if it just added configured mobs to it - so I would also suggest alongside this a feature in right-clicking with the Guide in hand opens a list of all of the creatures that the tome is currently configured to interact with and restores neutrality to(populated with wolves and bees by default).

There could also be a 'debug mode' that lets you see every creature the curse will attempt to interact with that it can find in the given modpack, just for the sake of transparency.

**Describe why you want this. If there's a reason.**

I want to make a pack where the Ring of Seven Curses is the default intended gameplay route, but I also like playing with the mod Alex's Mobs and I don't want a large portion of its content to be completely inaccessible because of the curse.

AM adds a lot of animals which are neutral by default, but may still have other interactions like taming them under specific circumstances or you might want to be around them without them constantly trying to murder you as though you killed their firstborn for any other reasons.

This could potentially be a problem for other mods which add mobs as well, but Alex's Mobs is the most obvious and relevant example I can think of right now. Currently I'm just blacklisting them from the curse altogether, but it almost feels cheap towards the intended gameplay alterations to do so - hence this suggestion!

**Comment by Aizistral** [comment]
The reason animals from Alex's Mobs don't count as such, I presume, is because for whatever reason they do not extend vanilla's `Animal` class, as that is the main criterion in determining whether or not the mob should be subject to curse-altering effect of the Guide. There is no hardcoded list of animals there, but a mere `instanceof` check.
Implementing configurable animal list wouldn't be hard, but for reason above it's not so easy to somehow display a full list of things that count as animals. I can do something like "Right-click with Guide in creative mode on a mob, and ye shall know whether it counts as animal or does not", but that's about it.

**Comment by Aizistral** [comment]
Technically the Guide's curse-altering effect doesn't have some hardcoded list of what mobs it affects - it merely checks if the mob extends vanilla's `TamableAnimal` class, which should generally cover most modded tamable animals as well. I presume for whatever reasons mobs from Alex's Mobs don't do that.

I can do the configurable list and some way to debug which entities count as affected by the Guide, but going for a full GUI listing them feels kind of excessive. Modpack developers can document such information by adding dedicated entry to The Acknowledgment, or to their own form of in-game guide, or in whatever way they prefer of all available to them.

**Comment by Aizistral** [comment]
Actually, thanks to the changes in Forge as of 1.13 I can't even get to know the entity class without having an instance of it available somehow, so there is no way I could programatically look through the entire entity registry to tell apart which entities extend that class and put together a complete list. I can still do something like "Right-click the entity with the Guide in creative mode, and ye shall know if it counts or not", but that'll be it.

**Comment by Not-February** [comment]
That would still be helpful!

As for the classes I'm not sure. I just know that Grizzly Bears are tameable under specific circumstances only(you have to get them to eat honey either as a dropped item in-world or from a beehive, and then feed them salmon similarly), and I still had one run at me from a mile away out for blood before I even saw it and had to nope out.

A lot of the mobs in the mod are tamed by dropping items on the ground rather than right clicking the mob, maybe that makes a difference in how they're detected?

**Comment by Aizistral** [comment]
> A lot of the mobs in the mod are tamed by dropping items on the ground rather than right clicking the mob, maybe that makes a difference in how they're detected?

I have no idea, but you could contact the developer of that mod and ask them.
