### ISSUE TITLE
Missing Config Options

### ISSUE THREAD

**Issue by Jusey1** [Extegral/Enigmatic-Legacy#262]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.15.0
 * Curios API: 5.0.6.0
 * Patchouli: 64.0
 * Forge: 39.0.59

#### Description of a Bug:
The "Save the Bees" and "Ring of Seven Curses" config related options are in the CLIENT file instead of the COMMON file. The new Seven Curses config option is in the COMMON file (I thought it would be CLIENT?).

#### How to Reproduce:
1. Generate configs.
2. Read them.

#### Logs:

Crash Log: N/A

**Comment by Aizistral** [comment]
Human factor, my old friend. Fixed in [2.15.1](https://github.com/Aizistral-Studios/Enigmatic-Legacy/commit/93f219f5a976ef46f354aecd973008493a121a2b).
