### ISSUE TITLE
Possible 1.15 update?

### ISSUE THREAD

**Issue by Windspren** [Extegral/Enigmatic-Legacy#27]
It sounds like it will be a while before a lot of mods are updated to 1.16, and most of the modpack makers I’ve talked to are planning around 1.15 instead of 1.14 due to its superior performance on servers. Would it be possible for a quick port to 1.15 to be made before the 1.16 port?

**Comment by Extegral** [comment]
Hm. I do actually have time now, and I am frequently requested to do this throughout the latest days. Guess I'll take some time and make it happen.
