### ISSUE TITLE
Не правильный перевод на русский язык

### ISSUE THREAD

**Issue by callfromvoid** [Extegral/Enigmatic-Legacy#270]
В русском описании Ангельского благословения, Ока туманности и Воли океана вместо делаю уязвимее к чему-то, написано делают неуязвимым к чему-то

**Comment by Aizistral** [comment]
Если б только на этом проблемы заканчивались. Глянь #225.

**Comment by Aizistral** [comment]
Ишшуй пожалуй прикрою, учитывая что правилам составления багрепорта он не следует, да и ошибки в локализации как баг трудно классифицировать. Тот на который я сослался выше в принципе исчерпывающе описывает положение вещей с локализацией.
