### ISSUE TITLE
Arrows reflected with Angel's Blessing Soulstone occasionally cause CTD

### ISSUE THREAD

**Issue by spezard** [Extegral/Enigmatic-Legacy#272]
Versions
 * Enigmatic Legacy: 2.15.1
 * Curios API: 1.18.1-5.0.6.0
 * Patchouli: 1.18.1-64
 * Forge: 1.18.1-forge-39.0.76 (also tested on 39.0.59)

Description of Bug:
Somewhat randomly, when the Angel's Blessing Soulstone's passive reflects an arrow, the arrow gains so much momentum it causes an instant CTD, and potentially a crash loop if the arrow is still loaded when logging back in (happened in multiplayer, had to clear the arrow with /kill). At least, I think that's what's happening. Best guess is the soulstone's other passive of applying increased projectile speed to your own projectiles is also applying to the reflected arrows, and sometimes goes screwy and applies some kind of exponential multiplier. The MC launcher text on crash reads;

```
The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
Exit Code: -1
```

Full crash log included, tested in a clean environment with no other mods installed besides those required. Though interesting to note, in this test the momentum values are only in the 7-8 digit range (presuming that's still way over the limit), but in the crash log from my original encounter (a custom modpack of around 100 mods), the momentum values were 245 digits, around 220 of which were zeroes at the end.

How to Reproduce:
1. Equip Angel's Blessing Soulstone
2. Stand near any skeleton (large numbers help, originally encountered the crash loop near a spawner, but I've had it happen on occasion when fighting single skeletons)
3. Wait for the reflect (rarely is the first one, not sure what triggers the crash arrow exactly)
4. ded

Crash Log: https://www.toptal.com/developers/hastebin/ecajevojus
(file attached as well just in case)
[crash-2022-02-14_23.35.37-client.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/8066005/crash-2022-02-14_23.35.37-client.txt)

**Comment by Aizistral** [comment]
While I was unable to reproduce this, I can confirm that deflected arrows pick up immense speed. Will try to fix this by restricting acceleration to only be applied once per projectile.
