### ISSUE TITLE
Bulwark of Blazing Pride StackOverflow

### ISSUE THREAD

**Issue by grundyboy34** [Extegral/Enigmatic-Legacy#276]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.16.0
 * Curios API: curios-forge-1.18.1-5.0.6.1
 * Patchouli: Patchouli-1.18.1-65
 * Forge: 39.0.75
 * Minecraft: 1.18.1

#### Description of a Bug:
Blocking with the Bulwark of Blazing Pride when a Guardian attacks causes a server/client crash due to StackOverflow.

#### How to Reproduce:
1. Equip Bulwark of Blazing Pride
2. Block as Guardian attacks

#### Logs:
Crash Log, user-provided: https://pastebin.com/VkTSyFb7
Crash Log, proper: https://gist.github.com/Aizistral/3ae1c1076293260dc431ad2ea7463de0

**Comment by Aizistral** [comment]
Provide full crashlog please. It doesn't help when stacktrace is cut off.

**Comment by grundyboy34** [comment]
It's a StackOverflow, that message repeats over and over until out of memory.

**Comment by Aizistral** [comment]
I requested it not because I am unaware. Whatever, reproduced this myself.

**Comment by grundyboy34** [comment]
Glad you could replicate. Sorry my logs couldn't be more helpful, I actually didn't have any that looked like the ones you posted.
