### ISSUE TITLE
Rings unequipping from each slot over base 2 when entering world

### ISSUE THREAD

**Issue by KolanoPigmeja** [Extegral/Enigmatic-Legacy#278]
Each time I enter my world a ring that was equipped in the third slot I've added gets unequipped.
It doesn't affect any other curios from this mod.

**Comment by Aizistral** [comment]
Though this is not a correct bug report, I think I know what issue you are talking about, and it most likely is on the side of Curios rather than my own mod. Have you used commands or config to add your extra slot?

**Comment by KolanoPigmeja** [comment]
Oh alright, makes sense. I've used _/curios add ring_.

**Comment by Aizistral** [comment]
Alright, thanks. I will close this for now, refer to the issue cross-referenced above your reply to see how investigation is going there or if you would want to add any details about your case which were not mentioned by someone else as of yet.
