### ISSUE TITLE
Angels Blessing not boosting velocity of some projectiles

### ISSUE THREAD

**Issue by Exlor64** [Extegral/Enigmatic-Legacy#279]
In the newest update 2.16.1 of the mod there's an issue with the angles blessing. It has the ability to boost the velocity of projectiles but this doesn't apply to all projectiles like potions and possibly snowballs. It also doesn't seem to work with some modded bows. More testing is needed.

**Comment by Aizistral** [comment]
Any submitted bug reports that disregard bug report template will not be reviewed. Please create another issue, following the template and properly filling in all requested data.
