### ISSUE TITLE
Ring of 7 Curses and Spectator Mode on death

### ISSUE THREAD

**Issue by LunafeyLazuli** [Extegral/Enigmatic-Legacy#284]
#### Versions (Be specific, do not write "latest"): 1.18.1
 * Enigmatic Legacy: 2.17.0
 * Curios API: 1.18.1-5.0.6.1
 * Patchouli: 1.18.1-65
 * Forge: 39.0.85

#### Description of a Bug:
A clear and concise description of what the issue is.
When a player has the Ring of 7 curses equipped, they are thrown into spectator mode when you die, and it does not go away until you disconnect and reconnect (sometimes also just completely disconnects you from the server). We think it may be a weird conflict with Corail Tombstone (version 7.4.1-1.18) This is also while being hosted on a server

#### How to Reproduce:
1. Equip the Ring of 7 curses
2. Die to literally anything
3. You are stuck in spectator mode and can move around and everything
4. Disconnect
5. Reconnect
6. Not in spectator mode anymore

#### Logs:
There aren't many logs related to the problem, this is what I'm able to get
https://www.toptal.com/developers/hastebin/beyayisena.sql

**Comment by LunafeyLazuli** [comment]
Side note, I do get disconnected from the server when ever I try to jump into a lava lake with the unholy stone to try to get rid of the ring
https://www.toptal.com/developers/hastebin/odixovehix.yaml

**Comment by Aizistral** [comment]
Could not reproduce, and hastebin links don't seem to be valid any longer.
