### ISSUE TITLE
Crash on client load

### ISSUE THREAD

**Issue by VioletChan311** [Extegral/Enigmatic-Legacy#287]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.17.3
 * Curios API: 5.0.6.3
 * Patchouli: 65
 * Forge: 1.18.1 - 39.1.0

#### Description of a Bug:
Game will not load after pressing 'PLAY' button. I have removed all mods and done a fresh install of the forge version and a separate installation. the error reads:

"
ERROR
Game crashed
An unexpected issue eccurred and the game has crashed. We're sorry for
the inconvience.

This crash may be caused by an invalid Java Runtime configuration. Check and custom configuration settings.

Exit Code: 1
"

note i have not changed any launch settings other than setting a new directory and changing the name of the installation.

#### How to Reproduce:
1. fresh intal forge for 1.18.1
2. install curios, patchouli and enigmatic legacy
3. press play
4. Behold!

#### Logs:
latest: https://www.toptal.com/developers/hastebin/uxezutufaw.yaml
debug: https://www.toptal.com/developers/hastebin/sumebehoca.yaml

**Comment by Aizistral** [comment]
It's really weird, but I don't really see anything that would indicate the reason of crash within your logs, or even that the crash occured to begin with. Can you post a crash report?

**Comment by VioletChan311** [comment]
so after a few hours of messing with it i downgraded curios API (moved to 5.0.6.2) and it works now. this is the crash report (https://www.toptal.com/developers/hastebin/qaruzaxeva.sql) so you can investigate as this obviously hasnt solved the issue itself, and just avoided it. let me know if theres any other stuff i can help with!

**Comment by Aizistral** [comment]
Ah, of course. Looks like 1.18.2 version of Curios declares itself as incompatible with 1.18.1:
![image](https://user-images.githubusercontent.com/47505981/156945411-08dc9762-436e-4a8c-8839-11775d4f878e.png)
I do not know if it has technical capability to be compatible, but either way it is beyond my influence.

**Comment by VioletChan311** [comment]
oh my lord i have no idea how i didnt see that, sorry about that!

**Comment by Aizistral** [comment]
Well, happens to the best of us.
