### ISSUE TITLE
Item Interactions

### ISSUE THREAD

**Issue by Tyrius1** [Extegral/Enigmatic-Legacy#29]
bit of an odd request: 
could you make it so that in order to use the Tome of Hungering Knowledge, you have to have it in your main hand and the enchanted item in your off-hand and shift right click? 

Same with Mending Mixture

This interactions would be something that i could use as a way for players to gain magic and smithing xp accordingly within Project MMO.

**Comment by Extegral** [comment]
Not really.

You can always use event listeners to catch crafting event and check what goes in and out. It's not that difficult.
