### ISSUE TITLE
Travel between waystones

### ISSUE THREAD

**Issue by Reniel80** [Extegral/Enigmatic-Legacy#294]
Possibility to craft the waystone and travel with your pets.

**Comment by Aizistral** [comment]
I honestly do not really like an idea of providing a way of warping to any arbitrarily bound location as part of this mod. There are items in the mod which are designed to permit some kind of waystone-like travel, like Extadimensional Eye or Potion of Recall, but they have limitations on where and what you can teleport, as to ensure that things stay balanced and that those existing items are not rendered useless by some kind of all-in-one alternative. Besides, there are other mods out there which give you exactly that.
