### ISSUE TITLE
[1.18.2] Shift the Ender Chest button when Quark is installed

### ISSUE THREAD

**Issue by BugmanBugman** [Extegral/Enigmatic-Legacy#295]
When Quark is installed, it's sort button feature overlaps with the ender chest button of this mod, making it difficult to distinguish and click between the 2. Perhaps shifting over a few pixels to the left could fix it?

![2022-03-31_20 05 25](https://user-images.githubusercontent.com/40730042/161178038-6a3e8d5d-c894-4319-b393-51def963862c.png)

**Comment by callfromvoid** [comment]
If you use the ender chest ring all the time, you can turn off sorting in the player's inventory in the Quark configuration. In any other inventory, including the ender chest, you can still sort your inventory

**Comment by Ozzi-Hero** [comment]
The config for the Ender Chest ring allows you to change the position of the button yourself.

**Comment by Aizistral** [comment]
As @Ozzi-Hero stated above, it is indeed possible to change position yourself though the client config. But I will consider the possibility to alter button placement automatically when Quark is installed, seeing as it is a common mod to be found alongside Enigmatic Legacy in modpacks.
