### ISSUE TITLE
Incorrect Required Mods Version for 1.18.1

### ISSUE THREAD

**Issue by WenXin20** [Extegral/Enigmatic-Legacy#296]
#### Versions (Be specific, do not write "latest"):
 * `Enigmatic Legacy: 2.18.0`
 * `Curios API: 1.18.2-5.0.6.3`
 * `Patchouli: 1.18.2-66`
 * `Forge: 39.1.2`

#### Description of a Bug:
- Enigmatic Legacy is marked as compatible with 1.18.1, but it requires Patchouli & Curios versions that only work on 1.18.2

#### How to Reproduce:
1. Install Enigmatic for 1.18.1
2. Install latest Curios & Patchouli versions for 1.18.1
3. The game does not load, Enigmatic requires `Curios API: 1.18.2-5.0.6.3` & `Patchouli: 1.18.2-66`
4. Install Curios & Patchouli for 1.18.2
5. The game does not load as the mod versions are only compatible with 1.18.2

#### Logs:

Crash Log: https://gist.github.com/WenXin20/83e508dc564ebbc31cad582c347ce536#file-latest-log-L480

**Comment by Ozzi-Hero** [comment]
v2.18 is for 1.18.2 and the listed dependencies are for 1.18.2.

Version 2.17.3 is the most recent version for 1.18.1 and can be found [here](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy/files/3668951)

**Comment by Aizistral** [comment]
My bad. Due to changes on the side of Forge in 1.18.2 there is no way I can make 1.18.2 versions compatible with 1.18.1/1.18, so it is indeed incorrect marking on my side.

**Comment by Aizistral** [comment]
It is now correctly marked as compatible only with 1.18.2.

**Comment by WenXin20** [comment]
Thanks, sounds good!
