### ISSUE TITLE
Update checker login message

### ISSUE THREAD

**Issue by Crabby-Gamer** [Extegral/Enigmatic-Legacy#30]
Only Forge, Curios, and Enigmatic Legacy were installed when testing.

#### Versions:
 * Enigmatic Legacy: 1.7.0
 * Curios API: 2.0.2.4
 * Forge: 31.2.23

#### Description:
Update checker for 1.7.0 says that 1.6.4 is the latest version and that you're out of date. Not much else to it.
![Capture](https://user-images.githubusercontent.com/46363164/85915886-3fe98200-b800-11ea-8289-e622d60ffbb3.PNG)

#### How to Reproduce:
Log in.

**Comment by Extegral** [comment]
Recheck if it still happens.

**Comment by Crabby-Gamer** [comment]
Seems to no longer happen, thanks!
