### ISSUE TITLE
The mod failed to load correctly

### ISSUE THREAD

**Issue by seanxiecn** [Extegral/Enigmatic-Legacy#300]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:2.17.3
 * Curios API:5.0.6.3
 * Patchouli:1.18.2-66
 * Forge:1.18.2-40.0.40

#### Description of a Bug:
A clear and concise description of what the issue is.
The game gave a failure message: Enigmatic Legacy (enigmaticlegacy) has failed to load correctly
#### How to Reproduce:
1. ...
2. ...
3. ...
4. Behold!

#### Logs:

[crash-2022-04-06_01.18.45-fml.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/8420520/crash-2022-04-06_01.18.45-fml.txt)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
Enigmatic Legacy 2.17.3 is not compatible with 1.18.2. You need to update to at least 2.18.0.
