### ISSUE TITLE
"Knowledge Points"?

### ISSUE THREAD

**Issue by Darkmega18** [Extegral/Enigmatic-Legacy#301]
**The question.**
What are "knowledge points" that are gained from reading the various recovered books and such from around the world, and what does this currently influence, if anything?
Can it be detected on a player for other purposes? Such as quests or scoreboards or advancements etc?

I thought it would be related to unlocking information in the book, however most things just seem to unlock when their sources are first touched instead.

**Comment by Aizistral** [comment]
They are currently only used to unlock certain lore entries in The Acknowledgment, and even those happen to have alternative ways of unlocking. Nowadays these points mostly serve as a reminder of all incredibly very stuff I planned to implement in future, before realizing that future might be a little more distant than expected.
Regarding detection, there is an advancement trigger which is fired whenever player receives knowledge points; you can see the example of it being used in `enigmaticlegacy:book/materials/etherium_ore` advancement. There are 3 knowledge point types: `overworld`, `nether` and `end`, each one awarded by ancient tomes found in respective dimension. Using trigger you can test total amount of knowledge points of chosen type whenever it is fired. There is also `generic` knowledge point type, which simply reflects sum total of 3 other types.

**Comment by Darkmega18** [comment]
oooh, wonderful. I can probably make use of this once I get motivated, given how much I reward and use these books. specifically the end ones as quest rewards and then unlock currencies in the same way once they're done being shared around.

Well, keep on it. You'll get to use it for more stuff later, hopefully. right?

**Comment by Aizistral** [comment]
Sure.
