### ISSUE TITLE
Elytra Relic

### ISSUE THREAD

**Issue by Reniel80** [Extegral/Enigmatic-Legacy#304]
Can you create Ancient Enchanted Elytras Relic with a Curios slot for it, compatible also with vanilla Elytras and "maybe" custom elytras can be equiped and be visible too. That would be perfect!!!

Reason: You will add a new unseen amazing objet to your collection and will solve at same time the problem of wearing elytras and chestplate together.

**Comment by Aizistral** [comment]
Can you elaborate on this "Ancient Enchanted Elytras Relic" thing? I don't think I understand exactly your idea as to what it should be and what it should do.

**Comment by Reniel80** [comment]
An Elytra Wings Relic with cool textures that allow you to FLY with boost at higher speed of normal elytras.. Something similar to when you use fireworks while flying and of course... as a relic it breaks too.
With a Curios Api slot to equip this relic allowing you also equip the minecraft elytras wings in this new slot, so doing this, you can equip elytras using a chestplate at same time, you know that elytra wing slot is by default the same chestplate slot in minecraft. Solving the classic issue once and forever of elytras and chesplates.

**Comment by Aizistral** [comment]
Added in 2.22.0.
