### ISSUE TITLE
Taking damage from soul fire even with the Non-Euclidean Cube equipped.  

### ISSUE THREAD

**Issue by Solbaify** [Extegral/Enigmatic-Legacy#307]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.19.0
 * Curios API: 1.18.2-5.0.7.0
 * Patchouli: 1.18.2-67
 * Forge: 40.0.46

#### Description of a Bug:
A clear and concise description of what the issue is.
The player still takes damage from soul fire even with the Non-Euclidean Cube equipped. 
#### How to Reproduce:
1. Have Non-Euclidean Cube equipped 
2. Walk into soul fire
3. Take damage
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
I think you'd actually take damage from normal fire as well, since they share the exact same damage type, but anyways.
