### ISSUE TITLE
Crashes after updating the mod in the server

### ISSUE THREAD

**Issue by Jayerd** [Extegral/Enigmatic-Legacy#308]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.20.0
 * Curios API: 1.18.2-5.0.6.3
 * Patchouli: 1.18.2-67
 * Forge: 1.18.2 (40.1.0)

#### Description of a Bug:
it crashes when I try to turn on the server

#### How to Reproduce:
1. ...
2. ...
3. ...
4. Behold!

#### Logs:

Crash Log: https://mclo.gs/i923PKa

**Comment by Aizistral** [comment]
Fixed in 2.20.1.
