### ISSUE TITLE
No-Sleep Penalty 7 Curses Config 

### ISSUE THREAD

**Issue by Moomsy** [Extegral/Enigmatic-Legacy#310]
**Provide a detailed and clear description of feature or change that you want to offer.**
 i am not sure but going into the playerdata - NBT explorer and looking for playerpersistent-enigmaticgift changing it from 1 to 0 changed the penalty. i mean if thats one way to change it for now thats okay but it would be great to add a config to toggle it or give the player the possibility to set a timer for it like :
 
 #no-sleep Penalty applied on playerdeath true/false
 
together with 

 #set time(in ticks) when no-sleep Penalty wears off after playerdeath if penalty is set to true  (Range -1-XXXXX) [[where -1 would be no timer at all and persistent penalty so the player ould never sleep again haha]]

**Describe why you want this. If there's a reason.**
Cheerio i am a big Fan of this mod and mostly coming back to it whenever i am making super hard Dungeon crawler Packs and/or Hardcore Packs for myself. I've used the Config plenty of times and i saw that the sleep-pentaly now is no longer able to be worked around with other mods like Sleeping inv pet or sleep charms.  Mostly i was fine with the toll of beeing careful but beeing able to work around it late game was an accomplishment for me. So not at all beeing able to skip nights after dying is pretty annoying.

**Comment by Moomsy** [comment]
Correcting myself after 10 more test tries- 

Playerpersist - enigmatic.gift: 0/1 does not change it, for some reason 9/20 times i was able to sleep trying back and forth in Creative vs Survival

**Comment by Aizistral** [comment]
Yeah, the tag you edited doesn't have anything to do with sleep curse, it's only used to keep track of players to which Enigmatic Amulet was granted when spawning into the world.

**Comment by Terra-B-Welch** [comment]
I know I'm gravedigging a little but...

Some option to allow a limited number of sleeps for a ring cursed player would be great, would help for a few mods that would require a specific amount of sleeping be done to progress them.
(Example: Abyss mod requiring the player to sleep twice to progress its story)

**Comment by Aizistral** [comment]
Implemented by e871aa9.
