### ISSUE TITLE
Configure add request

### ISSUE THREAD

**Issue by XiFengXF** [Extegral/Enigmatic-Legacy#311]
Is it possible to add a configuration to cancel Soul Shatter and Keep on Fire on the ring？
  For me, the author of the integration pack, other curses have a certain role in improving the challenge of the game, which is really good, but these two curses are really too difficult for ordinary players. I hope to add related configurations soon, thank you very much！

**Comment by Aizistral** [comment]
Wouldn't that make it Ring of the Five Curses?

**Comment by Aizistral** [comment]
I mean, for the abovementioned reason specifically there are no options that entirely disable the curse, only those that adjust their intensity. Soul loss can be made easier by restricting how much crystals players can loose until they will not loose anymore (up to only 1), and infinite burning can be easily addressed in any number of reasonable ways, starting from carrying around a water bucket. It's a bit more complicated in the Nether, but there you can still use water in combination with vanilla cauldron early on, and later just get some form of fire resistance.

**Comment by XiFengXF** [comment]
OK, but I still wish for a better configuration for each curse
