### ISSUE TITLE
about The Acknowledgment unlock ?

### ISSUE THREAD

**Issue by AlexYangCong** [Extegral/Enigmatic-Legacy#312]
**The question.**
dude，i'm pretty confuse right now. i'm playing a modpacks with my friend. and i'm the only one put on the ring. They took a lot of earth heart back, but i never seen them in the chest of any dungeon in overworld，and i cant find it in my guide book（The Acknowledgment） the guide book was too many locked item。 i can't find darkest scroll and it was locked in book either。when i kill the Wither still no Nefarious Essence, not unlock in my guide book again, and i read a lot of Tattered  Withered Corrupted book ,is the point show out (not exp)work for the guide book?is some thing i must unlock in my book then i can find it？can you tell me which move can unlock the item specifically？ thank you bro（i'm chinese , not an english speaker , sorry for my weird english)

**Comment by JaegerPhantom** [comment]
Maybe it is because it is a modpack? ask the maker of the pack first, it often is the reason why something doesn't work.

**Comment by AlexYangCong** [comment]
> Maybe it is because it is a modpack? ask the maker of the pack first, it often is the reason why something doesn't work.

Yes it  usually because that，but ，i was play with my friend....if modpack change , it will work for all of us right?  but  now, they didn't put on the ring but can get some resource more than me,who actually playing the part LOL. seem to be their book unlock diffrent to me. so i want to know the principle of The Acknowledgment unlock item.  seek item or kill or some magical way hhhh

**Comment by Aizistral** [comment]
Entries for Heart of the Earth, Darkest Scroll and Nefarious Essence are unlocked when you first obtain them. First two spawn randomly in loot of dungeons of the Overworld and Bastion Remnants respectively, and how often you get them is entirely up to the chance. Nefarious Essence, however, should always drop from Wither if you wear Ring of the Seven Curses; if it does not, then it is something on the side of modpack you are playing.

Knowledge points obtained by reading tattered/withered/corrupted books do not have any special use yet.
