### ISSUE TITLE
Non-Euclidian cube active ability bug

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#314]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.21.1
 * Curios API: 5.0.7.0
 * Patchouli: 67
 * Forge: 40.1.0

#### Description of a Bug:
Sometimes Non-Euclidian cube active ability fails to work on first use and produce a very strange bug, that do next:
- prevents Curios inventory to open;
- does not allow you to save the game (it just freezes on exit).

#### How to Reproduce (read the point 5 first):
1. Remove all saves from game directory.
2. Create new creative world and try to use NEc.
3. If bug not produced try to create another one creative world and try to use NEc.
4. If bug still not produced try to relaunch the Minecraft, then create another two creative worlds and try to use NEc on the second one.
5. Behold... I guess? Actually I'm not sure that this bug can be repeated in this manner because i still don't understand what actually triggering it. But time to time it happening for me like that.

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by arliegolden** [comment]
I also had this issue, but thought it was just me. Interesting that it’s a bug not my cursed computer!

**Comment by Tillllt** [comment]
If it helps somehow, i really know how to NOT produce and evade this bug. Need to put cube in Curios inventory without using it and save the game. After world reload with cube in Curious bug is not produced anymore. Also discovered with this that cooldowns dropped after world reload.
