### ISSUE TITLE
Architects Favor

### ISSUE THREAD

**Issue by ladukey** [Extegral/Enigmatic-Legacy#315]
I've read through the Acknowledgment and I cant find anything in there talking about how to gain the Architects Favor. I saw it was required for a couple items and I don't know what that even means and I cant find anything online about it. I've worn the cursed ring for about half my time in the world. Is it something that comes about naturally the more you play and discover?

**Comment by callfromvoid** [comment]
Architects Favor can only be worn by 'Devoted Believers' role holders on the mod developer's Discord server. It is personally awarded by the developer to active users

**Comment by Aizistral** [comment]
And the server is over there: https://discord.gg/fuWK8ns
