### ISSUE TITLE
Eye of the Nebula active ability issues

### ISSUE THREAD

**Issue by belathus** [Extegral/Enigmatic-Legacy#317]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.19.0
 * Curios API: 5.0.7.0
 * Patchouli: 1.18.2-67
 * Forge: 1.18.2-40.0.52

#### Description of a Bug:
The activated ability for the Eye of the Nebula lets you teleport behind an entity that you're looking at. Three problems I've noticed: there does not seem to be a range limit, this is not blocked by blocks, and this can teleport you into a block.

I decided to report this after accidentally teleporting myself from the surface, y=63, to y=-31. It was a surprise at the time, as I accidentally pressed the button to activate the ability. After some experimentation, I realized that this was repeatable.

#### How to Reproduce:
1. Equip eye of the Nebula
2. Look someplace where an entity is likely to be. Oceans are a good bet.
3. Spam the spellstone activated ability button.
4. Behold!

#### Logs:
Crash Log: N/A (not a crash)

**Comment by Aizistral** [comment]
> this is not blocked by blocks

Turns out this bit was fixed in 2.20.0. Range limit was always 32 blocks by default, and regarding teleportation into blocks... well, this is where I rely on player simply planning accordingly.
