### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Broonox** [Extegral/Enigmatic-Legacy#318]
There is an ongoing bug, which lets players not join the server after the first login. It keeps saying "internal exception: io.netty.codec.decoderexception: java.lang.illegalargumentexception: payload may not belarger than 1048576 bytes". After deleting the mod from the Server, all players could join and leave the server how often they want. I also tried to clean install with the mod so everything will install without any issues- but with failure. Any tips ?

The Server if there is Quark installed the Server will also not load, it will stuck at "Water ID 0". Removing "Enigmatic-Legacy" will remove this issue.

In both cases is no "crash/error path" in the logs so the problem is known to me

**Comment by Aizistral** [comment]
This is not a correct bug report. Please create another issue, selecting bug report template and following it:
![image](https://user-images.githubusercontent.com/47505981/166824530-323f7f95-5520-4c0b-acc1-0e9c7c35c8f7.png)
In the first case, regarding logs, you would need to aquire and examine client logs as well as server after someone gets the error. If nothing is there - check debug logs as well.
Furthermore, I advise creating a discrete issue for second bug.
