### ISSUE TITLE
Crash with Astral Sorcery for 1.15.2

### ISSUE THREAD

**Issue by Kevino36** [Extegral/Enigmatic-Legacy#32]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.7.0
 * Curios API: 2.0.2.4
 * Forge: 32.2.33

#### Description of a Bug:
Crashes on launch

#### How to Reproduce:
Launch the game

#### Logs:
https://pastebin.com/MHfS4fDZ

**Comment by Extegral** [comment]
I've tested this with Enigmatic Legacy 1.7.0, with Curios API 2.0.2.6 on Forge 32.2.33. Astral Sorcery version: 1.12.3, ObserverLib: 1.2.0.

Game started normally, extensive testing didn't show any compatibility issues.

**Comment by Extegral** [comment]
I am closing this due to absence of response. Comment here or create new issue in case it is still relevant.
