### ISSUE TITLE
Etherium Scythe does not till land

### ISSUE THREAD

**Issue by Thaumatarge** [Extegral/Enigmatic-Legacy#322]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.21.1
 * Curios API: 5.0.7.0
 * Patchouli: 1.18.2-57
 * Forge: 40.1.19

#### Description of a Bug:
The Etherium Scythe says it can till a 3x3 area of land, but it does not till any land. Scythe otherwise functions as advertised.

#### How to Reproduce:
Try to till any type of dirt with an Etherium Scythe.

#### Logs:
N/A

**Comment by Aizistral** [comment]
Props to Forge on this one. I was building against 40.0.34 and scythe worked perfectly fine there, but now that I updated to 40.1.19 it indeed does not work.
