### ISSUE TITLE
Astral Breaker not breaking melons as well as it should

### ISSUE THREAD

**Issue by Sebaty5** [Extegral/Enigmatic-Legacy#324]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:    2.21.1
 * Curios API:               5.0.7.0
 * Patchouli:                 67
 * Forge:                      40.1.0

#### Description of a Bug:
The astral breaker is not considered a preferred tool for mining melons. An axe however is. Since the breaker should be a multipurpose tool it should be able to act as a preferred tool towards melons.

#### How to Reproduce:
1. Place melons in a 3x3 or 5x5 configuration
2. Get Astral Breaker (preferrably enchanted with efficiency)
3. mine center melon block
4. **Behold!**
5. Only the center melon gets broken as if broken by hand

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by StygianNights** [comment]
Tested while testing #323 and #325. Astral breaker does indeed not work on pumpkins or melons.

**Comment by Sebaty5** [comment]
Moss is also not affected but netherwart blocks and wheat blocks are. Assuming that the Astral Breaker is supposed to also function as a breaking tool for hoe blocks (wheatblocks, netherwartblocks, moss and so on), this would be worth a look too.
