### ISSUE TITLE
The Ender Slayer Sweeping edge

### ISSUE THREAD

**Issue by theivensoul** [Extegral/Enigmatic-Legacy#325]
#### Versions:
 * Enigmatic Legacy: 2.21.1
 * Curios API: curios-forge-1.18.2-5.0.7.0
 * Patchouli:Patchouli-1.18.2-69
 * Forge: 40.1.19

#### Description of a Bug:
The Ender Slayer's anti-teleport ability does not apply when hitting Endermen/Shulkers with sweeping attack.

#### How to Reproduce:
1. Get The Ender Slayer;
2. Hit some Endermen with sweeping attack;
3. Witness as they teleport away like nobody's business.

#### Logs:

Crash Log: *Unapplicable*.

**Comment by StygianNights** [comment]
Tested it in a server while tested #323, Confirmed that the enderslayer will not apply the anti-teleport effect if hitting adjacent collateral targets.
