### ISSUE TITLE
Option to Make Etherium Armor Visable

### ISSUE THREAD

**Issue by ghost** [Extegral/Enigmatic-Legacy#326]
I think an option to make Etherium armor visible would be nice as the item textures are already cool, a model for the armor would be just as nice. This could be configurable in some way so that people that still want it invisible can have that and people who want to see their hard earned gear also have the option to have a model for the armor.

**Comment by Aizistral** [comment]
There are two reasons why etherium armor does not have model:
1. Work needed to create a decent model;
2. It would overlap with shield animation.
