### ISSUE TITLE
Will of the Ocean Multiplayer Crash

### ISSUE THREAD

**Issue by l0Peace0l** [Extegral/Enigmatic-Legacy#33]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.8.1
 * Curios API: 1.16.1-3.0.0.1
 * Forge: 32.0.98

#### Description of a Bug:
Locally hosted multiplayer server crashes when I try to activate the Will of the Ocean's active ability.

#### How to Reproduce:
1. Start and join your own multiplayer server
2. Equip Will of the Ocean
3. Get enough XP to cast it
4. Press K
5. Booted to main menu, server is offline

#### Logs:

Crash Log: https://pastebin.com/xrB2vWGJ

**Comment by Extegral** [comment]
All thanks to debug log lines I did forget to remove in PacketSpellstoneKey's handler. Magnificent.
