### ISSUE TITLE
Architects favor issue

### ISSUE THREAD

**Issue by Jacob345k** [Extegral/Enigmatic-Legacy#333]
Problem: You have to talk to dimwits on a dead discord server to get architects favor
How to reproduce: Go to https://www.reg.ru/whois/aizistral.com and send mail
Solution: Bruh dont lock stuff behind talkwalls

**Comment by callfromvoid** [comment]
It's not a bug, it's a feature

**Comment by Jacob345k** [comment]
Smashing your balls with a rock is also a feature

**Comment by fw4hre0xxq** [comment]
Hey, I'm also experiencing this issue. When will it be fixed?

**Comment by Jacob345k** [comment]
Emotional Affirmation paywall type, do you need your mommy to wipe for you?

**Comment by MrMcBad** [comment]
Hey, I'm also experiencing this issue. When will it be fixed?

**Comment by callfromvoid** [comment]
If you don't want to communicate on a dead (because you don't want to communicate on it as well) server, you will only lose one item. That said, it does develop the community. So we will sacrifice you

**Comment by Jacob345k** [comment]
You see, you have to suck off a crackhead behind a 7-11 to be able to afford insulin this month. Since you don't want to, no insulin for you!

**Comment by callfromvoid** [comment]
I feel sorry for you, I advise you to call the toll-free helpline to deal with addiction

**Comment by Jacob345k** [comment]
ACtually loled

**Comment by Jacob345k** [comment]
In all seriousness, though, locking an item behind a 'go talk to people' sucks, especially in a few years when everyone uses skype premium or something

**Comment by callfromvoid** [comment]
things might change in a few years. For now, it's working well

**Comment by fw4hre0xxq** [comment]
It isn't working well, I can't use the item.

**Comment by Aizistral** [comment]
Besides the disregarded bug report template, described behavior is completely intentional. If you were willing to suggest change you should have used Feature Request template, or better yet - discussed it on the very same Discord server we are talking about. Unless of course you don't see yourself approaching the matter more professionally than you did here, in which case either way would be a futile effort.
