### ISSUE TITLE
waystones that aren't supposed to be breakable can be broken indirectly with a etherium pickaxe

### ISSUE THREAD

**Issue by kuba26038** [Extegral/Enigmatic-Legacy#334]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: EnigmaticLegacy-2.21.1
 * Curios API: curios-forge-1.18.2-5.0.7.0
 * Patchouli: Patchouli-1.18.2-67
 * Forge: 40.1.23

#### Description of a Bug:
the waystones mod has an option to make naturally generating waystones unbreakable. i enabled this issue and disabled the waystone's recipe on my server, where i realised that if you mined a block (only stuff breakable by pickaxes afaik) next to the waystone the waystone would break too. this is a problem i'm pretty sure i can't fix, so it's up to you. 

also a video: https://youtu.be/M7C0ytwRyj0

#### How to Reproduce:
1. install the waystones mod
2. enable worldgen waystone unbreakability via it's config
3. find a naturally generated waystone
4. place a stone block next to it 
5. break the block
6. Behold! you now illegally aquired a waystone.

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Sebaty5** [comment]
Can confirm that the "Unbreakable" Waystones from "waystones-forge-1.18.2-10.0.0.jar" are indeed breakable by the AOE of the Etherium Pickaxe and Astral Breaker.

**Comment by Aizistral** [comment]
Fixed in https://github.com/Aizistral-Studios/Enigmatic-Legacy/commit/4a3c540a1b848fa8e17bd905e84ca98d00570705.
