### ISSUE TITLE
Kicked upon entering Nether - Multiplayer, Custom made modpack

### ISSUE THREAD

**Issue by Rat-CK** [Extegral/Enigmatic-Legacy#343]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: [Release 2.22.0]:
 * Curios API: [1.18.2-5.0.7.0] 
 * Patchouli: 1.18.2-69
 * Forge: 40.1.31

#### Description of a Bug:
Custom made modpack, same issue as #335 
Kicked from nether upon entering - Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.EOFException: field size is too long! Length is 2 but maximum is 0.

#### How to Reproduce:
1. Enter Nether on Multiplayer.
2. Behold kicked!

#### Logs:
sorry about the length of this log, there is a shorter one after
((long log)) 
[22:45:01] Onwards:

((Secondary Shorter log))
 [22:55:08] Onwards:

(I never do issue reports, so apologises if its not great)

**Comment by Aizistral** [comment]
I don't see anything that would indicate errors on the side of Enigmatic Legacy in your log. How did you conclude the fault is on its side?

**Comment by Rat-CK** [comment]
Ah if it is not on the Enigmatic Legacy side, Do not worry 😅 .
I am mostly filling out this issue log as the modpack creator has been a bit busy, and the issue persisted even after update. Do excuse this issue log then sorry about that. Can you however see what possible be cause just as a helpful hint?

**Comment by Aizistral** [comment]
I don't see any errors there at all. Considering this is a client log, that's probably an indication that errors occurs on the side of server.

**Comment by Rat-CK** [comment]
Ah, well thank you anways!! Thank you, And sorry for the miss-issue logging😅
