### ISSUE TITLE
Amethyst blocks do not count as valid for Astral Breaker

### ISSUE THREAD

**Issue by Thaumatarge** [Extegral/Enigmatic-Legacy#344]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.22.1
 * Curios API: curios-forge-1.18.2-5.0.7.0
 * Patchouli: Patchouli-1.18.2-69
 * Forge: 40.1.31

#### Description of a Bug:
Amethyst blocks do not count as valid for Astral Breaker.

#### How to Reproduce:
1. Create world
2. Place or find amethyst blocks
3. Try to break them with the astral breaker
4. Behold, as they aren't affected by the AoE

**Comment by SoulRacer65** [comment]
Can confirm that this is what's happening
