### ISSUE TITLE
How to acquire "Heart of the Abyss"? (1.18.2)

### ISSUE THREAD

**Issue by ThisWeirdGuy** [Extegral/Enigmatic-Legacy#345]
Hello, I am playing on a server with friends, and I am having trouble figuring out how to acquire the "Heart of the Abyss" item. I have read through The Acknowledgement, tried researching online, read through the wiki, and have done some testing in a singleplayer creative world and still cannot find out how to acquire it. I am aware that you need the Ring of Seven Curses to get it (I'm the only one on the server who equipped the ring and I have had it one for the amount of time needed), but the Acknowledgment section for the Heart of the Abyss doesn't seem to give any information on how it is acquired, and I haven't seen this question asked before here on the subject.

Thank you for your help in advance.

**Comment by StygianNights** [comment]
I promise, during the normal course of minecraft, you would encounter it, but in short (stolen from the Enigmatic Legacy Discord FAQ): 


> **Q:** How do I obtain Heart of the Abyss?
> **A:** Once you have reached the mark of 99.5% of the time in the world spent bearing the Seven Curses, slay the Ender Dragon. Heart will appear at the location of dragon's demise, and will remain suspended in the air, never despawning, immovable and untouchable for anyone besides you.


Hope this helps!

**Comment by StygianNights** [comment]
As an addendum: you have to strike the dragon at least once during the fight. It will not spawn if you do not do so. If someone else kills the dragon without you, just respawn it with the vanilla end crystal method.

**Comment by ThisWeirdGuy** [comment]
Thank you! I just tested this in a singleplayer world and it worked!
