### ISSUE TITLE
I found a typo in the book entry for the amulet

### ISSUE THREAD

**Issue by vizthex123** [Extegral/Enigmatic-Legacy#346]
Shouldn't it say "brought here"?
![image](https://user-images.githubusercontent.com/31721920/172967806-56cab571-2a11-406d-b667-257dfa907453.png)

Feels a bit wrong to make a report for something so minor, but I'll update this if I find anymore.

**Comment by Aizistral** [comment]
> Feels a bit wrong to make a report for something so minor

Thanks nevertheless. You are encouraged to report any typos and errors you find, insofar I do not re-read my own texts nearly often enough to catch them all.

**Comment by vizthex123** [comment]
lol yeah, and yeah i'll do that. I personally dislike having a ton of small issues in separate posts, which is why i like to combine them all.

but yeah, i'll report any others i find.
