### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by Althraxion** [Extegral/Enigmatic-Legacy#347]
When you have the inscrutable eye or the charming insignia and a secondary charm with eternal binding, by taking off the eye or insignia, you duplicate the secondary charm.

**Comment by Aizistral** [comment]
This is not a valid bug report. Try once more and actually follow report template. I need to know at least which versions of mods Enigmatic Legacy depends on you use.

**Comment by StygianNights** [comment]
This doesn't appear to be a bug with the most recent version, at the very least. It will sometimes create a momentary desync between the internal server and the singleplayer client, but it goes away the moment you attempt to interact with it.
