### ISSUE TITLE
Crash on world load as of Patchouli 1.18.2-70

### ISSUE THREAD

**Issue by Ozzi-Hero** [Extegral/Enigmatic-Legacy#350]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.23.1
 * Curios API: 5.0.7.0
 * Patchouli: 70
 * Forge: 40.1.0

#### Description of a Bug:
Game crashes during world creation. Appears to be caused by a mixin failing during apply.

#### How to Reproduce:
1. Open instance with just EL and dependencies installed
2. Create world
3. Wait
4. Behold!

#### Logs:

Crash Log: [Whoosh!](https://mclo.gs/W3UdQAZ)

**Comment by Ozzi-Hero** [comment]
Upon further testing, it seems this is only an issue with the most recent version of Patchouli (uploaded 3 hours ago). I was able to successfully create a new world using v69 of Patchouli.

**Comment by Thaumatarge** [comment]
Can confirm this has happened to me too. I am not sure if it is the exact cause, but Patchouli 70 has done some changes to the rendering of the books to make fluids work inside the books.
