### ISSUE TITLE
A bad crush lead to quit on 1.18.2

### ISSUE THREAD

**Issue by Pinkhai** [Extegral/Enigmatic-Legacy#355]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:2.24.0
 * Curios API:5.0.7.0
 * Patchouli:69
 * Forge:40.1.25
cealus:3.0.0.2
#### Description of a Bug:
when i build a world and enter it i will quit

#### How to Reproduce:
1. open minecraft
2. build a world
3. enter it 
4. Behold!

#### Logs:

[错误报告（crash report）-2022-6-20_16.26.38.zip](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/8939026/crash.report.-2022-6-20_16.26.38.zip)

Crash Log: Please use a paste site like [Github Gists](https://gist.github.com).

**Comment by Aizistral** [comment]
Update to Patchouli 1.18.2-70.
