### ISSUE TITLE
Multiple Enigmatic Amulets does not apply their effects. 

### ISSUE THREAD

**Issue by DarkScorn** [Extegral/Enigmatic-Legacy#357]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.18.2-2.24.0 
 * Curios API: 1.18.2-5.0.7.0
 * Patchouli: 1.18.2-70
 * Forge: 1.18.2-40.1.41

#### Description of a Bug:
When a player equips more than one enigmatic amulet, only the first amulet apply its effects, any other does not.

#### How to Reproduce:
1. Have a mod or something increases talisman slots. (For me it is Cyclic mod)
2. Enable equipping more than one enigmatic amulet in config.
3. Take two same or different (doesn't matter) enigmatic amulets in creative, put them into talisman slots and see if they apply or not.
4. Behold!

**Comment by Aizistral** [comment]
Player is not intended to have more than one amulet, so I won't fix this.
