### ISSUE TITLE
at com.integral.enigmaticlegacy.helpers.PatchouliHelper.setEntryState

### ISSUE THREAD

**Issue by B-Wither** [Extegral/Enigmatic-Legacy#359]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.24.0
 * Curios API: 5.0.7.1
 * Patchouli: 71.1
 * Forge: 40.1.51

#### Description of a Bug:
Unknown error, happens sometimes when I get achievement (like obtaining blaze rod), and sometimes breaking ore (like diamond, nether quartz), but I really don't know why that happens, but game crashes.

#### Logs:
https://gist.github.com/B-Wither/1ce2b7bbe4f9935b7a85c47ba68a5944

**Comment by JJon149** [comment]
Yo, first time on github. I am reporting the same issue. I have got the same error running the latest version of Patchouli and Enigmatic Legacy, and tried down grading both, on two different launches. Still giving me some errors. If someone could look into my log and confirm this is the same issue and or let me know what's up!
Thanks!

[crash-2022-06-27_04.19.51-client.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/8991528/crash-2022-06-27_04.19.51-client.txt)
