### ISSUE TITLE
Game crashes when picking up certain items

### ISSUE THREAD

**Issue by Faith6001** [Extegral/Enigmatic-Legacy#362]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.24.0
 * Curios API: 5.0.7.1
 * Patchouli: 71.1
 * Forge: 40.1.52
 (Tested in 1.18.2)

#### Description of a Bug:
A clear and concise description of what the issue is.
When you pick up certain items like gold, diamonds or iron it crashes the game. Only happens on initially entering the inventory, subsequent pickups work just fine.
Possibly related to #359 

#### How to Reproduce:
1. Open Minecraft with just EL and dependents
2. Create a new world
3. Acquire iron/gold/diamond
4. Behold!

#### Logs:

Crash Log: https://gist.github.com/BennetBfkg/b6c0a2e4d82c5da2ededfe90d5a648a9
Latest Log: https://gist.github.com/BennetBfkg/e3a06b819b4745b225df3db9a7328a5b

**Comment by slottwo** [comment]
Same error here, and in same version. This also happens when I equip certain items like the one with an eye that talks to you and comes in the bonus chest when starting the game.

**Comment by Aizistral** [comment]
> Same error here, and in same version. This also happens when I equip certain items like the one with an eye that talks to you and comes in the bonus chest when starting the game.

I already uploaded 2.24.1 which fixes this.
