### ISSUE TITLE
Issue when added to All The Mods 7

### ISSUE THREAD

**Issue by Tezerz** [Extegral/Enigmatic-Legacy#366]
Versions 
 * Enigmatic Legacy: 2.19.0
 * Curios API: 5.0.7.1
 * Patchouli: 70
 * Forge: 40.1.31

Description of a Bug:
When added to all the mods 7, you will be able to load up the title screen and load in to a singleplayer world. After a few seconds the game process will freeze and you will be prompted with this org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered.

 How to Reproduce:
1. Install Enigmatic Legacy 2.19.0 from CurseForge
2. Drag and drop into the mod folder of ATM7
3. Launch a singleplayer or multiplayer world
4. Behold!

 Logs: CRASH
https://gist.github.com/Tezerz/9733d15906568e1d35f16d1e53d18ac4
           Latest
https://gist.github.com/Tezerz/25ceb0bd5ce47f4bd3c04c9ed3136a11

**Comment by Aizistral** [comment]
You are using incompatible Patchouli version, it has to be 71.1 at least.
