### ISSUE TITLE
Clicking "singleplayer" button on homescreen crashes game, when  "enigmatic_transience" file is in a world file

### ISSUE THREAD

**Issue by Norarabbits** [Extegral/Enigmatic-Legacy#368]
Versions:
 * Enigmatic Legacy: 2.24.1
 * Curios API: 5.0.7.1
 * Patchouli: 71.1
 * Forge: 40.1.54

Description of a Bug:
Clicking "singleplayer" button on homescreen crashes game, when  "enigmatic_transience" file is in a world file. When I remove the file I can access my worlds menu again. Maybe a rendering error? Is this trying to add something to the save, similar to the "cursed mode" text?

How to Reproduce:
1. launch game
2. have world file with "enigmatic_transience" JSON file in saves folder.
3. press "singleplayer"
4. crash

Logs:
Crash Log: https://gist.github.com/Noahboy007/8a374f5b5c2c7653e03138a382af9685.js

- In case the first link doesn't work.

[crash-2022-07-05_14.03.43-client.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/9048960/crash-2022-07-05_14.03.43-client.txt)

**Comment by Alexsist** [comment]
Got the same error
[crash-2022-07-15_14.37.37-client.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/9120493/crash-2022-07-15_14.37.37-client.txt)

**Comment by MattB70** [comment]
Another log with the error
https://gist.github.com/MattB70/13a29ff66ce54ab5a996fd50bfde8296#file-crash-txt
