### ISSUE TITLE
Issues with the ring of 7 curses

### ISSUE THREAD

**Issue by acrssims** [Extegral/Enigmatic-Legacy#369]
Me and my friends play on a server running Better Minecraft [Plus] 1.18.2. Recently our % of time suffering with the ring of 7 curses has gone down even though we put the ring  on as soon as we started. It went from 100% to 99.7% to 99%. So now we can no longer progress further into the benefits of the ring. Has anyone else had this problem, and is there anyway to fix it?

**Comment by Aizistral** [comment]
You're likely using older Enigmatic Legacy version. This bug was fixed in 2.20.0.
