### ISSUE TITLE
Emblem of Monster Slayer recipe change

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#37]
Due to Nether Update i think it will be good to change Axe of Executioner's recipe with some netherite stuff: diamond axe to netherite axe and/or iron ingots to netherite scrap/ingots.
UPD: And maybe an Emblem of Monster Slayer too.

**Comment by Extegral** [comment]
I just took a quick trip to the past and added netherite ingots to Axe of Executioner's recipe in an update released 3 hours ago.

On the other note, it's a pretty fair point about the emblem, I will definitely alter it's recipe in the next update.

**Comment by Tillllt** [comment]
Cool! I will rename thread then.
