### ISSUE TITLE
How to disable the inscrutable eye

### ISSUE THREAD

**Issue by Matteo-04** [Extegral/Enigmatic-Legacy#371]
I found the inscrutable eye in a chest in the end, activated it (also when I activated it my minecraft crashed) and at first it seemed to do nothing, I inquired a little on the internet, but then I gave up and put it in a chest without even wearing it.  Lately I started hearing this voice with some writings that appeared on the screen in certain situations, I admit that the first time I am also drifting and now it starts to get annoying.  I tried to click on the item also with the Shift, but nothing.  Is there any way to disable it?

**Comment by PaterFrog** [comment]
the eye also crashed me just now. I did hear the voice immediately though.
[crash-2022-07-09_18.44.55-server.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/9077544/crash-2022-07-09_18.44.55-server.txt)

Edit: Further crashes have not occurred for me as yet. I appear to be doing just fine. I assume the initial turn from Dormant Eye to Inscrutable Eye caused the crash.

**Comment by leftbones** [comment]
I'd also like a way to disable the voiceover.

**Comment by Aizistral** [comment]
As of now there is no way to retroactively disable it.

> the eye also crashed me just now.

Please submit a bug report in accordance to bug report template.
