### ISSUE TITLE
Visual bug for other players when wearing the magnetic ring

### ISSUE THREAD

**Issue by leftbones** [Extegral/Enigmatic-Legacy#373]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.24.1
 * Curios API: 1.18.2-5.0.7.1
 * Patchouli: 1.18.2-71.1
 * Forge: 40.1.51

#### Description of a Bug:
When I wear the magnetic ring, other players around me say that when they break blocks or otherwise do something to make items drop on the ground, they see the items fly towards me, even if I have the ring disabled. The items are then invisible (for them) and they can still pick them up, but can't see them.

#### How to Reproduce:
1. Wear the magnetic ring and disable it
2. Have another player nearby break a block

**Comment by callfromvoid** [comment]
I confirm
