### ISSUE TITLE
Nefarious Essence

### ISSUE THREAD

**Issue by Bigozz99** [Extegral/Enigmatic-Legacy#374]
Hey, so me and my friends are playing on a better minecraft plus server and two of us put on the ring in hopes nefarious essence would drop from the wither but upon killing it 5 times it has failed to drop any. Is there any item we are supposed to use or something because we were told it would drop on killing it. we are now stuck with the rings and seeing no future of being able to craft the unholy stone since it needs the nefarious essence. please help.

**Comment by PikachuGabe** [comment]
Is there progressive bosses? That mod has cause issues for me before. You will either have to turn off its custom drop(which dont work anyways) in configs or remove the mod.

**Comment by Aizistral** [comment]
This can only be a conflict with other mod. Reproduce and submit a bug report in accordance to bug report template.
