### ISSUE TITLE
The Scroll of Eternal Wisdom does not work as it should

### ISSUE THREAD

**Issue by Ri-Tirs** [Extegral/Enigmatic-Legacy#376]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.12
 * Curios API: 1.16.5-4.0.8.1
 * Patchouli: 1.16.4-53.2
 * Forge: 40.0.24

#### Description of a Bug:
I press Shift+RMB and the scroll is activated (the "Absorption" mode is turned on). When I just press RMB in order to change the mode so that the scroll does not take the experience but gives it away, then it turns off (as if I pressed Shift+ RMB for the second time). No matter how hard I tried, I couldn't take my experience away. The scroll does not want to change its mode to the one I need. How can this be fixed? (I'm playing on an assembly that I didn't assemble. About 190 mods)

(There were no failures and there are none. But the scroll does not want to work as it should)

#### How to Reproduce:
1. Just created a scroll and started using it. Does not want to change the mode to the one that is needed

**Comment by Aizistral** [comment]
Could not reproduce. Test without other mods, if you find out there's a specific mod responsible for this bug then report accordingly.
