### ISSUE TITLE
Config for limited number of sleeps with ring of seven curses

### ISSUE THREAD

**Issue by Terra-B-Welch** [Extegral/Enigmatic-Legacy#379]
**Provide a detailed and clear description of feature or change that you want to offer.**
I'd like to see a config option to allow the player to sleep x number of times before the no sleep curse kicks in.

**Describe why you want this. If there's a reason.**
It would be nice for some mods that require sleeping once or twice to progress their mods, a notable example being the abyss 2: the other side, where the player must sleep twice in order to advance the mod's starting storyline.

**Comment by Aizistral** [comment]
I have something different planned to solve that problem, see #151.

**Comment by Aizistral** [comment]
Also `DisableInsomnia` config option will be added in final release for 1.18.2, which should work as a solution until I implement a better one.
