### ISSUE TITLE
по какой-то причине со вчерашнего дня мод начал крашиться и вылетать, хотя за пару часов до произошедшего все отлично работало.

### ISSUE THREAD

**Issue by Bebrabek** [Extegral/Enigmatic-Legacy#380]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:
 * Curios API:
 * Patchouli:
 * Forge:

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. ...
2. ...
3. ...
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [Github Gists](https://gist.github.com).

**Comment by Aizistral** [comment]
Please make another issue and fill in the data properly.
