### ISSUE TITLE
Incompatible with latest 1.18.2 AppleSkin version

### ISSUE THREAD

**Issue by squeek502** [Extegral/Enigmatic-Legacy#383]
AppleSkin issue: https://github.com/squeek502/AppleSkin/issues/202

The signature of `shouldShowTooltip` has changed which is breaking [your mixin](https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/1.18.X/src/main/java/com/integral/enigmaticlegacy/mixin/MixinTooltipOverlayHandler.java).

There is now a way to do what you want without a mixin using the AppleSkin API. Usage instructions are here: https://github.com/squeek502/AppleSkin#for-mod-developers

**Comment by itsdinkd** [comment]
Can we get this released?
