### ISSUE TITLE
Picking up Soul Crystal while having >10 hearts crashes

### ISSUE THREAD

**Issue by jlaine3333** [Extegral/Enigmatic-Legacy#386]
Using SOL Carrot, I have more than 10 hearts of maximum health. Picking up a Soul Crystal at this point causes the game to crash.

**Comment by Aizistral** [comment]
Please make another issue, select "Bug Report" as a template and fill in all the requested data.
![image](https://user-images.githubusercontent.com/47505981/186876512-29676f44-af06-43cf-903c-94ef51cac3ec.png)
