### ISSUE TITLE
Location of file for the time spent cursed

### ISSUE THREAD

**Issue by Izakde** [Extegral/Enigmatic-Legacy#387]
Hello,

Is there a location in a server’s files or individual player’s data where the time spent cursed is stored? I wish to reset it since I would need to spend 200 real life days to get to 99.5% and I am not against resetting my player data on the server. I just want to know if resetting player data would actually reset the time spent since it seems from people’s discussions online that it is saved separately from the player data. Since this is related to a server and not single player world I do not want to reset the entire server and ruin the experience for those I play with.

And help is appreciated. Thank you!

**Comment by Aizistral** [comment]
`<world_save>/stats/<player_uuid>.json`. There are two stats, `play_time_with_seven_curses` and `play_time_without_seven_curses`. Both are measured in ticks
