### ISSUE TITLE
PVP config options

### ISSUE THREAD

**Issue by brybry251** [Extegral/Enigmatic-Legacy#388]
Is it possible to add options in the config to make it so that certain items don't affect other players? Perhaps have it togglable on the item itself like the Charm of the Treasure Hunter?

The reason this would be helpful is that I made the Testament of Contempt, but when I wear it, the debuffs apply to players around me, which makes it very difficult to play cooperatively with my friends

**Comment by Aizistral** [comment]
Testament of Contempt is designed that way. Live with the tradeoffs or don't use it at all.
