### ISSUE TITLE
Survival schematics and building patterns

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#39]
Maybe it's very crazy idea in general and cause of that I'm not sure about writing this thing here, but anyway.
What if we have that option in survival? Craft some special schematic import/export block in late game that allow us export buildings in schematics with XP cost or import them with relevant consist blocks cost.
In other words for export we place this block and after using it take some sort of interface where we can choose the size and position of export area with arrow buttons ( it's not convenient just writing coordinates like in classical creative schematic block but it can be the second input variant), can see covered area, how much XP it cost to save schematic and press "Save".
If switch to import we take the similar arrow button interface and covered area vision but with placing only (without sizing), choose schematic from list, store all consist blocks that schematic file needed here (that special schem. block actually need storage function in interface and consist block info about file for that) and press "Build". After that it autobuilding block by block (guess instant building cause lags).
Actually this thing can give us sort of "New game+ Survival" where we take with us our building progress.

About building patterns idea. If we will have some sort of instrument that can fast copypaste area. That is to say we pick area on "Attack" button and place it with "Use item" button with consuming consist blocks from our inventory.

I understand that this things may be very complicated and difficult to create but that would be very nice options in Enigmatic Legacy.

**Comment by Tillllt** [comment]
UPD: More about building patterns - it will be very great if that instrument will have 2 modes - standart and random. Standart just copied as is and random chaotically swaps blocks in pattern.

**Comment by Extegral** [comment]
This might be a cool idea but Enigmatic Legacy isn't the mod to be implementing it. I haven't made extensive research, but am pretty sure there are plenty of other mod's out there aimed specifically at operating with such ideas and developers interested in implementing them. Even more important, mechanic you outlined deserves it's own mod, as it would require a lot of work to ensure compatibility with something more than vanilla and a lot of time to discover and fix countless ways in which it will unvoidably be breaking.
