### ISSUE TITLE
Game Crash: Loading Client

### ISSUE THREAD

**Issue by viiizee** [Extegral/Enigmatic-Legacy#390]
* Enigmatic Legacy: 2.24.1
 * Curios API: 5.0.7.1
 * Patchouli: 71.1
 * Forge: 1.18.2 - 40.1.73

Description of a Bug:
Game crashes when trying to load the client.

How to Reproduce:
1. Load the client.
2. Behold!

Crash Log: https://gist.github.com/viiizee/72656c008eb072dd830fc60f8f727a15

**Comment by Aizistral** [comment]
This is not related to Enigmatic Legacy. Your client crashes due to model from some mod named "fishofthieves" failing to load.
