### ISSUE TITLE
`GolemHeartExcludedArmor` option does not work properly

### ISSUE THREAD

**Issue by Jusey1** [Extegral/Enigmatic-Legacy#394]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.26.0
 * Curios API: 5.1.1.0
 * Patchouli: 77.0
 * Forge: 43.1.52
 * Minecraft: 1.19.2

#### Description of a Bug:
The client config option "CursedRingDisplayLore" doesn't work at all while the common config option "GolemHeartExcludedArmor" only works on vanilla items ("minecraft:"). I tested the latter with only just the Enigmatic Legacy, following the proper rules to do so. I did mention this config option not working in the discord before, but been too lazy to make this post. Only recently doing so as I was working on the config for my 1.19.2 modpack and notice another config not working properly. I will update this post if I find more.

I have tested in both my modpack and in an instance with only just Enigmatic Legacy + it's required mods. The issues still persists, though my video recording was done only in the modpack.

#### How to Reproduce:
1. Simply change the config option or add a non-vanilla item to the other.
2. See that it didn't work in game.

#### Logs:
N/A for Logs as nothing appears during the logs in relation to these errors. However, I will share my configs and a video evidence below of it not working for me.

https://user-images.githubusercontent.com/61861078/201580587-0b6cc9f7-5db4-413c-bfb2-3cdb1db03c84.mp4

[configs.zip](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/9999841/configs.zip)

**Comment by Aizistral** [comment]
`CursedRingDisplayLore` works as intended. It doesn't hide description of curses and functionality, it hides specifically lines that describe origin of the item.

**Comment by Jusey1** [comment]
> `CursedRingDisplayLore` works as intended. It doesn't hide description of curses and functionality, it hides specifically lines that describe origin of the item.

Ooooh. I misread the config itself then. My bad.
