### ISSUE TITLE
Bulwark of Blazing Pride does not render properly

### ISSUE THREAD

**Issue by Jusey1** [Extegral/Enigmatic-Legacy#397]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.26.2
 * Curios API: 5.1.1.0
 * Patchouli: 77.0
 * Forge: 43.1.52
 * Minecraft: 1.19.2

#### Description of a Bug:
Essentially, the Bulwark of Blazing Pride is in item form and cannot be used. Attempting to block with it will cause a quick use animation and nothing more comes from it.

#### How to Reproduce:
1. Load game, get into world.
2. Get shield & have requirements to use it.
3. Doesn't work.

#### Logs:
-Nothing in the logs as far as I can tell but have this picture to show it not working properly.
![Untitled](https://user-images.githubusercontent.com/61861078/202042014-3af2dc72-c822-4263-b9fd-8d5c6fc9e6a8.png)

**Comment by Aizistral** [comment]
I have confirmed that it does not render correctly; however, functionally it's still completely usable.
