### ISSUE TITLE
[1.14.4] Crash on Startup with Forge 102

### ISSUE THREAD

**Issue by Thorf13** [Extegral/Enigmatic-Legacy#4]
#### Versions:
 * Enigmatic Legacy: 1.1.0
 * Curios API: 0.24
 * Forge: 1.14.4 102

#### Description of a Bug:
Crashes after hitting 100%, before the “Joining world...” text appears.

#### How to Reproduce:
1. Load with Forge version 102. (I tested from 93 to 102, and all of them produced this crash; 91 is the last version that works.)
2. Start a singlplayer game and watch it crash just before you enter the world.

#### Logs:

This one is with Forge 102 as noted above, with no other mods:
https://hastebin.com/raw/ekajezokad

In case it helps here’s my regular game’s one too, with a ton of mods:
https://hastebin.com/raw/mofecudeta

It appears to be almost exactly the same error — just the ASMEventHandler number is different.

**Comment by Extegral** [comment]
You have the same issue as this one: #3

**Comment by Thorf13** [comment]
Oops. Sorry about that!
