### ISSUE TITLE
The Golden Ring doesn't makes Piglins Neutral due to old code

### ISSUE THREAD

**Issue by Jusey1** [Extegral/Enigmatic-Legacy#402]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.26.4
 * Curios API: 5.1.1.0
 * Patchouli: 77.0
 * Forge: 43.2.0

#### Description of a Bug:
The Golden Ring simply will not make Piglins Neutral due to some old code that I saw in the source which needs to be updated.

It needs to be:
	@ Override
	public boolean makesPiglinsNeutral(SlotContext slotContext, ItemStack stack) {
		return true;
	}
	
Currently, it is:
	//@ Override
	public boolean rendersPiglinsNeutral(String identifier, ItemStack stack, LivingEntity wearer) {
		return true;
	}
	
I proposed the fix to the source code already.

#### How to Reproduce:
1. Wear Ring.
2.Go near Piggys (while not wearing cursed ring).
3. Behold!

#### Logs:
Crash Log: N/A

**Comment by Aizistral** [comment]
I assure you that it does work; currently Enigmatic Legacy just uses its own mixin to ensure that this effect is applied. We have simply not migrated to Curios-based approach yet.
