### ISSUE TITLE
Enigmatic crashes both client and server

### ISSUE THREAD

**Issue by OxiiGiin1** [Extegral/Enigmatic-Legacy#403]
https://pastebin.com/E78mPH5a

**Comment by Cherrychip7** [comment]
having the exact same issue

**Comment by Aizistral** [comment]
This is not a valid bug report. Please create a new one following the report template. From provided log it seems likely that there is a conflict with other mod in your modpack; in that case you'll have to determine what exact mod causes this and include it's name and version in your report.
