### ISSUE TITLE
Stats get registered under the minecraft resource key

### ISSUE THREAD

**Issue by JustRed23** [Extegral/Enigmatic-Legacy#404]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.18.2-2.25.0
 * Curios API: 1.18.2-5.0.7.1
 * Patchouli: 1.18.2-71.1
 * Forge: 1.18.2-40.2.0

#### Description of a Bug:
Stats get added to the minecraft: namespace. I am working on a mod that looks for ResourceLocations in the registry that do not belong to the minecraft namespace. Your stats (ex. 'play_time_with_seven_curses' (EnigmaticLegacy:L678)) get registered under the minecraft: namespace. See ![image](https://user-images.githubusercontent.com/21986809/210845158-67078e7f-2cd7-46bb-b2df-841f3f69e39f.png)

A better way of doing this would be by passing the ResourceLocation two times during register.
Right now you are using `register(Registry, String, ResourceLocation)` but `register(Registry, ResourceLocation, ResourceLocation)` would be better for this.

#### How to Reproduce:
1. Boot up the server
2. Wait for the message '[Enigmatic Legacy/INFO]: Registering stats...'
3. Have a mod that loops through all ResourceLocations in Registry.CUSTOM_STAT and prints them to the console
4. Behold!

#### Logs:

Crash Log: 
[latest.log](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/10354311/latest.log)

**Comment by wolflord212312** [comment]
I made a pull request with the fix #405 i have tested on magma and forge and nothing seems to be broken,awaiting Aizistral
