### ISSUE TITLE
Mod configuration not working/saving

### ISSUE THREAD

**Issue by Vicky-Valery** [Extegral/Enigmatic-Legacy#406]
#### Versions (Be specific, do not write "latest"): Minecraft: 1.19.2
 * Enigmatic Legacy: 2.26.4
 * Curios API: 5.1.1.0
 * Patchouli: 77
 * Forge: 43.2.0

#### Description of a Bug:
A clear and concise description of what the issue is.
When i tried to edit the configuration, specifically for the save the bees, wich neutral mobs shouldnt be affected by the curse and enderman anger range and ramdom teleport values, they save in the file, but after i open the game and get into an world, another file is created and is labbeled like this: enigmaticlegacy-common.omniconf_20230106_181701, wich is an ERRORED file type, and in this file the custom configuration is saved, but the enigmaticlegacy-common file where it should have saved the configuration, and even tho the errored file is there edited, bees still attacked me, even with save the bees set to true

#### How to Reproduce:
1. edit the common configuration file
2. launch the game and enter into a world
3. check the files again
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [Github Gists](https://gist.github.com).

**Comment by Stepler167** [comment]
i can't find "disable Enigmatic Amulet/Ring of the Seven Curses from being granted to player when they spawn"
config. How it's called " ?

**Comment by Aizistral** [comment]
> i can't find "disable Enigmatic Amulet/Ring of the Seven Curses from being granted to player when they spawn" config. How it's called " ?

It's in Accessibility Options, specifically it's `RingoftheSevenCursesEnabled`.

**Comment by Aizistral** [comment]
Regarding your issue, @Vicky-Valery, this is not a bug; most likely you're just incorrectly formatting the list of neutral mobs you're trying to add. You may join my [Discord server](https://discord.gg/fuWK8ns) if you want to get help with that.
