### ISSUE TITLE
Dedicated server crash 1.16.1 1.8.4

### ISSUE THREAD

**Issue by pabthelamb** [Extegral/Enigmatic-Legacy#41]
#### Versions:
 * Enigmatic Legacy: EnigmaticLegacy-1.8.4
 * Curios API: curios-FORGE-1.16.1-3.0.0.1
 * Forge: forge-1.16.1-32.0.106

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. Attempt to start server
2. Crash

Crash Log: https://hastebin.com/docafegeko.sql

**Comment by Extegral** [comment]
Try to copy config files of Enigmatic Legacy (enigmatic-legacy-common.toml & enigmatic-legacy-client.toml) from client to server config folder, that should work as quick fix if you need one. I figured out the cause of the issue and it will be no more in next update.

**Comment by pabthelamb** [comment]
thanks
