### ISSUE TITLE
Angel blessing/Eye of nebula crash on server. 

### ISSUE THREAD

**Issue by awesomestpie** [Extegral/Enigmatic-Legacy#410]
#### Versions (Be specific, do not write "latest"): 1.18.2
 * Enigmatic Legacy: 2.25.0
 * Curios API:5.0.7.1
 * Patchouli:71.1
 * Forge:40.1.76

#### Description of a Bug:
Crashes Client when using active ability. Crashed Server once

#### How to Reproduce:
1. Equip Angel blessing/eye of nebula
2.  Double jump
3. Crash
#### Logs:

[crash-2023-01-19_15.34.03-client.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/10456768/crash-2023-01-19_15.34.03-client.txt)
[crash-2023-01-10_22.30.31-server.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/10456774/crash-2023-01-10_22.30.31-server.txt)

Crash Log: Please use a paste site like [Github Gists](https://gist.github.com).

**Comment by Aizistral** [comment]
Unfortunately I do not indend to release any further mod updates for 1.18. You may reopen this if you encounter such an issue in newer versions.
