### ISSUE TITLE
Problem with Infinitum UndeadProbability not working properly

### ISSUE THREAD

**Issue by SoulRacer65** [Extegral/Enigmatic-Legacy#414]
#### Versions:
 * Enigmatic Legacy: 2.26.5
 * Curios API: 5.1.2.2
 * Patchouli: 77
 * Forge: 43.2.0

#### Description of a Bug:
When trying to change the line in the config from anything other than the default "85" it doesn't register that the change was made, doesn't cause a crash or other currently noticed problems

#### How to Reproduce:
1. navigate to the "enigmaticlegacy-common" file
2. change the "TheInfinitumUndeadProbability" to whatever number you want
3. do /reload or restart the game and see if it works or not

#### Logs:
N/A

**Comment by Aizistral** [comment]
This is a display issue. The probability does change, it's just that the tooltip fails to reflect it.
