### ISSUE TITLE
Dying to Iron Golem with Ring of Seven Curses crashes server

### ISSUE THREAD

**Issue by ThePlagueDoctor** [Extegral/Enigmatic-Legacy#415]
Currently running the pack "TC World on Fire" which is a pack on the ATLauncher and Curse Forge. We've seemed to narrowed it down to specifically when you seem to die to a mob while wearing the ring, unsure of why though. Hoping you can help! If you need anything else than below or I made a mistake in filling out the template, let me know please and I'll correct it.

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.12
 * Curios API: 4.0.8.2
 * Patchouli: 53.3
 * Forge: 36.2.34

#### Description of a Bug:
A clear and concise description of what the issue is.
Server crashes on TC World on Fire when dieing to an Iron Golem while wearing Ring of Seven Curses. 

#### How to Reproduce:
1. Put on Ring of Sever Curses
2. Aggro iron golem by existing
3. Get killed by golem
4. Behold! Crash!

#### Logs:
Crash Log
https://gist.github.com/ThePlagueDoctor/0cff9657b2ccdd8e572c6bec27927adc

**Comment by Aizistral** [comment]
Unfortunately I do not indend to release any further mod updates for 1.16. You may reopen this if you encounter such an issue in newer versions.
