### ISSUE TITLE
[1.18.2]  Increased TPS demand from mobs with Enigmatic Legacy

### ISSUE THREAD

**Issue by Reshy** [Extegral/Enigmatic-Legacy#421]
With Enigmatic Legacy Installed
![2023-05-24_12 27 34](https://github.com/Aizistral-Studios/Enigmatic-Legacy/assets/2096384/898c027e-5e35-4155-bafb-88f8d0f238f0)
Without Enigmatic Legacy Installed
![2023-05-24_11 38 54](https://github.com/Aizistral-Studios/Enigmatic-Legacy/assets/2096384/9a5b9c16-d540-44fa-abfe-eaf482eeb3b1)

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:  EnigmaticLegacy-2.25.0.jar
 * Curios API:  curios-forge-1.18.2-5.0.9.0.jar
 * Patchouli:  Patchouli-1.18.2-71.1.jar
 * Forge:  40.2.4

#### Description of a Bug:
There seems to be an issue with larger modpacks that causes a noticeable increase in entity (especially pillager) TPS when enigmatic Legacy is installed.  I'm not sure what specifically causes it, but removing Enigmatic Legacy seems to resolve the issue.  Could be a conflict with another mob that I don't know of, but I wanted to report this anyway.

#### How to Reproduce:
1. Load up a World with Enigmatic Legacy installed
2. Using a tool, the TPS will be noticeably higher than normal.

#### Logs:
Not a log-related issue, seems to be more back-end related.

**Comment by Aizistral** [comment]
Unfortunately I do not indend to release any further mod updates for 1.18. You may reopen this if you encounter such an issue in newer versions.
