### ISSUE TITLE
com.aizistral.enigmaticlegacy.handlers.SuperpositionHandler.getCurseAmount

### ISSUE THREAD

**Issue by windy664** [Extegral/Enigmatic-Legacy#428]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:2.26.5
 * Curios API:1.19.2-5.1.4.1
 * Patchouli:1.19.2-77
 * Forge:1.19.2-43.2.4

#### Description of a Bug:
The server timed out while processing certain tasks with the Enigmatic Legacy mod, causing the server to crash. The issue seems to be related to dealing with enchantment related quests.

#### How to Reproduce:
1.Start a Minecraft server with the Enigmatic Legacy mod.
2.Play the game, especially those related to enchanting.
3.Watch to see if the server crashes while processing these tasks.
4. Behold!

#### Logs:
[crash-2023-07-08_15.30.42-server.txt](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/11989654/crash-2023-07-08_15.30.42-server.txt)

**Comment by Aizistral** [comment]
I don't think this is an issue with Enigmatic Legacy's enchantment queries. From the stacktrace it appears that the server timed out when processing vanilla method from `EnchantmentHelper`, which should not have taken long. Needless to say I have not encountered such issue before or received reports thereof, and I'm afraid that without extensive profiling it's hard to understand what's going on in your specific case, and whether that is a fault of Enigmatic Legacy or not.
