### ISSUE TITLE
CDT after die

### ISSUE THREAD

**Issue by VirayaDraco** [Extegral/Enigmatic-Legacy#43]
I was playing fine with your mod EnigmaticLegacy-1.8.2.jar and all others mods i have instaled together until i donwload the versions 1.8.4 and 1.8.5 of your mod.

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: EnigmaticLegacy-1.8.4.jar & EnigmaticLegacy-1.8.5.jar (i can only play with the EnigmaticLegacy-1.8.2.jar)
 * Curios API: curios-FORGE-1.16.1-3.0.0.2
 * Forge: forge-1.16.1-32.0.107-installer & forge-1.16.1-32.0.108-installer

#### Description of a Bug:
When i die the game save itself and CDT, and i cant load the world after that

#### How to Reproduce:
1. ... Just find a mob and let it kill you and die
2. Behold!

#### Logs:

Crash Log
https://hastebin.com/opazahesin.rb

latest.log
https://hastebin.com/ipaboxohiv.md

**Comment by Extegral** [comment]
And where are the logs

**Comment by Extegral** [comment]
I am closing this in favor of issue #44 as outlining this same crash, but presenting cleaner testing data and better formatting.
