### ISSUE TITLE
Setting "CursedRingdisableInsomnia" to true in the config does not disable 7 curses-related phantom spawning

### ISSUE THREAD

**Issue by NyanMC** [Extegral/Enigmatic-Legacy#431]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.26.5
 * Curios API: 5.1.4.1
 * Patchouli: 1.19.2-77
 * Forge: 43.2.21

#### Description of a Bug:
A clear and concise description of what the issue is.
After setting CursedRingdisableInsomnia to true in the config, phantoms will still spawn regardless of how long it has actually been since the player last slept, as long as the ring is equipped. I checked what appeared to be responsible for phantom spawning from this mod (MixinPhantomSpawner.java) and found no checks related to this config option, implying that the option does not actually affect phantom spawns whatsoever. Given the config option claims to "prevent curse of insomnia from actually doing anything" and not just the part related to the inability to sleep, this feels like a bug.

If this is intended behavior, this config option has a terrible name.

#### How to Reproduce:
1. Set "CursedRingdisableInsomnia" to true in the config
2. Create a new survival world (make sure the difficulty is set to something other than peaceful, but I probably didn't need to tell you that)
3. Equip the Ring of the Seven Curses and wait for night (or use cheats to set the time to night immediately)
4. Behold! Phantoms will spawn on the first night despite the config change disabling insomnia.

#### Logs:
not applicable

**Comment by Aizistral** [comment]
That's not intended, it appears that I have indeed forgor (💀) to add a check for that option in the mixin. I'll fix this as part of 1.19.3 update.
