### ISSUE TITLE
Crash on death while Enigmatic Amulet is equipped with Optifine installed

### ISSUE THREAD

**Issue by Delsato** [Extegral/Enigmatic-Legacy#44]
Tested with only Curios, Enigmatic Legacy, and Optifine on Forge 1.16. 
Couldn't recreate the crash without Optifine.

Versions:
 * Enigmatic Legacy: 1.8.5
 * Curios API: 3.0.0.2
 * Forge: 32.0.107
 * Optifine: 1.16.1 HD U G2

Description of a Bug:
Whenever Optifine is installed, and you die while having the Enigmatic Amulet equipped, game freezes, you'll be kicked to the "Saving world" screen then the game crashes.

How to Reproduce:
1. Load any world with previously mentioned mods
2. Equip Enigmatic Amulet
3. Die to anything, or just /kill
4. Behold! Big fat crash :(

Log:
https://hastebin.com/isaxucajug.sql

Crash Log:
https://hastebin.com/xebefaxapo.php

**Comment by Extegral** [comment]
I was able to reproduce it through testing, but logs appear very generic and completely unrelated to Enigmatic Legacy rendering calls, therefore leaving no clues what exactly within my code could possibly cause this. It's gonna take some time before I can figure it out.

This crash doesn't seem to happen on Forge 32.0.98, the exact version OptiFine changelog points to as supported. It is possible that issue might end up being completely on the side of OptiFine.

**Comment by Extegral** [comment]
Should hopefully work now.
