### ISSUE TITLE
Wayfinder of the Damned Biome Bug

### ISSUE THREAD

**Issue by NeonEthan** [Extegral/Enigmatic-Legacy#445]
Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.25.0
 * Curios API: 1.18.2-5.0.9.1
 * Patchouli: 1.18.2-71.1
 * Forge: 1.18.2

Description of a Bug:
Using the Wayfinder of the Damned in the nether can be a bit buggy. If you enter the Minecraft Biome Soul Sand Valley, the Wayfinder compass stops working completely, as if there are no soul crystals in the world.

How to Reproduce:
1. Die in the nether
2. Obtain Wayfinder of the Damned compass
3. Explore the nether, see how the compass is working.
4. Locate a Soul Sand Valley biome, enter it, and see the compass stops working.
5. Behold!

Unfortunately most of my soul crystals are lost to this, and I'm unsure what to do! I have not found any biomes, either Overworld or the Nether, that break this yet besides Soul Sand Valley. 

Edit: Tested both in Singleplayer as well as on a Multiplayer server. Versions did not change throughout this test.

**Comment by Toastr125** [comment]
Intended mechanic for lore reasons. Read the Wayfinder's entry in The Acknowledgement.

**Comment by Aizistral** [comment]
Yes, it is an intended behavior. You may still use the compass to triangulate the position of your crystals. If you don't feel like engaging with this fancy mechanic, there's a also a `soul_archive.json` file in your world save folder which you may check directly to retrieve exact coordinates.

**Comment by Aizistral** [comment]
I dunno maybe I should add a config to turn this feature off

**Comment by NeonEthan** [comment]
> Yes, it is an intended behavior. You may still use the compass to triangulate the position of your crystals. If you don't feel like engaging with this fancy mechanic, there's a also a `soul_archive.json` file in your world save folder which you may check directly to retrieve exact coordinates.

Looked in the soul_archive.json file, and the only deaths in that file are of my friend in the Overworld. Nothing showing of my soul crystals missing in the Nether. I currently have about 7 hearts, and had 13 before this happened.

**Comment by NeonEthan** [comment]
Can Soul Crystals be destroyed/despawn? I triangulated one of my soul crystals, so now I am at 8 hearts out of 13. However now the compass is showing no soul crystals are anywhere when I pull it out, no matter the biome.
