### ISSUE TITLE
[Feature Request] Add config to only allow the player who owns a soul to pick it up

### ISSUE THREAD

**Issue by darkphan** [Extegral/Enigmatic-Legacy#45]
I would be handy if there was a config option to only allow the player who owns the soul to pick it up.

On a multiplayer server other people can simply pick up someone's gear if it went into the soul instead of a gravestone type mod (where most of those only allow the player whose grave it is to access)

**Comment by Extegral** [comment]
I suppose you mean Extradimensional Vessel, right?

I was primarily implementing it with possibility for every player to pick it up, since otherwise it would render all PvP completely pointless. But having a config option for that seems to be a fair enough choice.

**Comment by darkphan** [comment]
Ah yes, I wasn't actually sure what it was called I had made an assumption. Could there also be an option to just enable/disable the Vessel as well?

**Comment by Extegral** [comment]
Both requested options are now present in 1.8.6 release.
