### ISSUE TITLE
"Spellstone active ability" button crash

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#47]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: Since 1.8.0 (and later)
 * Curios API: 3.0.0.2
 * Forge: 32.0.108

#### Description of a Bug:
If press "Spellstone active ability" button without spellstone. Crash causes if you have not found any spellstones yet. No other mods used.
[crash-2020-08-15_20.37.29-client.txt](https://github.com/Extegral/Enigmatic-Legacy/files/5079211/crash-2020-08-15_20.37.29-client.txt)

#### How to Reproduce:
1. Create new world
2. Press "Spellstone active ability" button
3. ...
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Extegral** [comment]
```
java.lang.NullPointerException
	at com.integral.enigmaticlegacy.handlers.SuperpositionHandler.lambda$getSpellstone$1(SuperpositionHandler.java:155)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at com.integral.enigmaticlegacy.handlers.SuperpositionHandler.getSpellstone(SuperpositionHandler.java:152)
	...
```

Ah shit, here we null again.

At least it only happens when spellstone slot isn't unlocked yet. Will be fixed in upcoming major update.
