### ISSUE TITLE
Dimensional Anchor Dispenser Charging

### ISSUE THREAD

**Issue by CraftyZombie** [Extegral/Enigmatic-Legacy#511]
**Provide a detailed and clear description of feature or change that you want to offer.**

Vanilla Respawn Anchors can be charged by an adjacent dispenser with glowstone blocks inside. I think it'd be great if the same thing was implemented with ender pearls for the Dimensional Anchor.

**Describe why you want this. If there's a reason.**

This would create more consistency with the base game, and allow for basic automation of recharging if a player bothered to set it up.

**Comment by Aizistral** [comment]
Already implemented dummy :3

**Comment by CraftyZombie** [comment]
Uh oh, something is very wrong with my client then lol 😅

**Comment by CraftyZombie** [comment]
Alrighty, so the cause of this was Supplementaries. It allows dispensers to teleport by shooting ender pearls. I imagine this would have to be fixed on their end, right?

**Comment by CraftyZombie** [comment]
https://github.com/MehVahdJukaar/Supplementaries/issues/1107

Will be fixed in next Supplementaries update.
