### ISSUE TITLE
Update Channel Bug - Client showing New Update but latest version is installed. 2.30.1

### ISSUE THREAD

**Issue by Zelioth** [Extegral/Enigmatic-Legacy#524]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.30.1
 * Curios API: 5.9.1
 * Patchouli: 1.20.1-84
 * Forge: 47.3.7

#### Description of a Bug:
Client when in single player or server it is reporting there is an update "2.30.0" but the latest version installed is 2.30.1

![image](https://github.com/user-attachments/assets/4107f476-4930-4ab1-91f4-72fcdc06e28b)

**Comment by Aizistral** [comment]
Is fixed 👍
