### ISSUE TITLE
Mining shulker boxes with aoe pick (astral breaker, etherium pick) will delete contents inside the shulkers mined other than the targeted box.

### ISSUE THREAD

**Issue by llssc** [Extegral/Enigmatic-Legacy#56]
Using 1.8.4 since I'm on a server and I never asked the owner to update the mod yet.

Put three shulkers in a row, put something in each, and try to mine the middle one.
It will only preserve the contents of the one in the middle.

**Comment by Tillllt** [comment]
Same problem here in singleplayer. At first faced this in survival, but can't understand circumstances and here it is.
