### ISSUE TITLE
Player corruption on death

### ISSUE THREAD

**Issue by Aizistral** [Extegral/Enigmatic-Legacy#58]
#### Versions:
 * Enigmatic Legacy: 2.2.0
 * Curios API: FORGE-1.16.1-3.0.0.2
 * Patchouli: 1.16-39
 * Forge: 1.16.1-32.0.67

#### Description of a Bug:
Sometimes whenever player dies, their character gets stuck with zero health in a completely unkillable state, unable to normally interact with the world and with death animation repeatedly played. This state persists upon reloading that world and there's seemingly no way to fix it other that completely erasing player data from save file.

It is yet to be figured out whether this issue is caused by Enigmatic Legacy, whether it can happen in multiplayer and exact circumstances that cause it to emerge.

**Comment by Aizistral** [comment]
I have not encountered this since porting to 1.16.3, either due to temporary solution here: https://github.com/Extegral/Enigmatic-Legacy/blob/ecd661ff7de2c7116950e304d1d12952e2e94c70/src/main/java/com/integral/enigmaticlegacy/handlers/EnigmaticEventHandler.java#L571

...working a lot better than I expected it to, or due to it not existing anymore.

This issue might be a subject to re-opening in future, but I guess we can dismiss it just yet.

**Comment by felipenunezz** [comment]
the issue is not solved, in servers if you hit a player with the judgment the player experiences this
