### ISSUE TITLE
Etherium tools and Nether wood small defect

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#59]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.1.3
 * Curios API: 3.0.0.2
 * Patchouli: 1.16-39
 * Forge: 32.0.108

#### Description of a Bug:
It seems that Astral Breaker is not effective at all against Warped, Crimson stems and their derivatives. Etherium Waraxe is effective, but mines them without aoe. No other mods used (but it was not necessary i guess).

#### How to Reproduce:
Try to use Etherium tools against some Nether wood.

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
Guess they've added some more incredibly very custom block materials™ that I missed out on. I will check this and fix in next update, which will be rolled out in a couple days.
