### ISSUE TITLE
Crash upon using Anvil for 1.3.0

### ISSUE THREAD

**Issue by Gingerbreadman32** [Extegral/Enigmatic-Legacy#6]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.3.0
 * Curios API: 1.0.0.3
 * Forge: 28.1.0

#### Description of a Bug:
Forge server will crash upon any player using an Anvil. The error describes an issue with the PacketAnvilField.java under the decode method.

#### How to Reproduce:
1. Start a forge 28.1.0 server with all the necessary mods.
2. Join the server and right click an anvil.

#### Logs:
https://pastebin.com/SqsgHaQG

This log has mods but I was able to recreate on a server with only this mod as well.

**Comment by Extegral** [comment]
It should now work fine. I am not sure, hovewer, whether the mechanics behind The Architect's Inkwell and Lore Fragment (which caused the issue in the first place) will behave perfectly on server in every single case. Report if you notice any problems.
