### ISSUE TITLE
Angel's Blessing push mechanic in blast off from ground

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#62]
**The question.**
I understand that i push myself further with jump, but i can't figured out how it works with Elytra on start from ground. From time to time i can blast off with different force and go up in the range of 50-100 blocks on Y coord. But today i literally launched myself into space (see the screenshot). Is it some conditions here that allow you to do that kind of things or is it just random?
![2020-09-09_13 03 51](https://user-images.githubusercontent.com/69244323/92590072-42f2fb00-f2a4-11ea-8f85-5aa0f46dff73.png)

**Comment by Tillllt** [comment]
It is one push, just in case.

**Comment by Aizistral** [comment]
Christ, you certainly _pushed_ things over the limit there.

Ideally the velocity generated by Angel's Blessing should add up to current velocity, but numbers it adds are fixed. This isn't the case when Elytra flight is active though, there is an additional calculation going there that makes instantaneous velocity gain decay expotentially in proportion to current velocity, to prevent infinite acceleration. Does this extreme boost only happen when elytra wings are open already? I suspect something in my formula might cause the opposite effect when player is techically flying but their current velocity is very close to zero. You can help by doing additional testing to confirm/disprove this assumption.

Also it's a subject for it's own bug report, I guess.

**Comment by Tillllt** [comment]
Ok, i will try to test it.
