### ISSUE TITLE
Nerf The Acknowledgement

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#63]
I'm very appreciate the joke that it shall incinerate those who refuse to embrace it but seriously, if Acknowledgement is used like a weapon it seems that it's a bit OP. It's reachable on start, damage in the middle of stone and iron sword and very fast atack speed, besides it can burn the foes and can't broke. Can you reduce the damage at least?

**Comment by Aizistral** [comment]
Well, I tried to choose the stats so that it would be just a solid choice of weapon in the early game, quickly getting outdated as it cannot be enchanted, but it appears I misguessed the resulting power. What exact stats would you offer?

**Comment by Aizistral** [comment]
Also gotta say
> ![image](https://user-images.githubusercontent.com/47505981/92597907-e4565e80-f25c-11ea-8117-a58259316aaf.png)

...I felt that.

**Comment by Tillllt** [comment]
> What exact stats would you offer?

An average in 3.5-4.5 i guess, so with 1.9 atack speed DPS can be  about 7.6-8.5 (almost like stone sword).
Maybe it will be good  to make 3 damage and 2.5 or even 3 atack speed so it can be more like if we use the book like a weapon IRL (very often repetetive strikes). But then it will become a weapon with most fast atack speed in Enigmatic Legacy (more than Scythe), so i don't know what is better here.


> ...I felt that.

Yeah. And then you make something like Max Payne's face when you notice this.
