### ISSUE TITLE
Angel's Blessing extreme velocity with Elytra start up

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#65]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.1.3
 * Curios API: 3.0.0.2
 * Patchouli: 1.16-39
 * Forge: 32.0.108

#### Description of a Bug:
Sometimes when Elytra takeoff is using with Angel's Blessing it generates a colossal velocity that launch you on giant distances. I didn't quite understand how it works, but it can happen when you quickly enter in flying mode and then press AB push with small delay. As far as I understand, timings are very important here. The whole procedure takes no more than half a second. Tested without other mods too.

#### How to Reproduce:
1. Wear Angel's Blessing and Elytra outdoors. It is advisable to raise the camera's view by about 45 degrees so as not to crash into something.
2. Fast press jump button twice and then press AB push button. It may not work right away, but after several attempts it should.
3. ...
4. https://upload.wikimedia.org/wikipedia/commons/c/cc/Gagarin-Poyekhali.ogg

![2020-09-09_18 29 04](https://user-images.githubusercontent.com/69244323/92629548-245a2780-f2d7-11ea-8741-4af843f6c5fe.png)
While testing it without other mods i set a new record. Yay!

PS: It would be a pity to fully lose such a feature. Maybe you can just nerf it to some adecuate limits and leave it like a flight boost mechanic?
#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Tillllt** [comment]
>From #62 : Does this extreme boost only happen when elytra wings are open already?

Definitely yes.

**Comment by Aizistral** [comment]
> Maybe you can just nerf it to some adecuate limits and leave it like a flight boost mechanic?

This is exactly what I plan to do.

**Comment by Tillllt** [comment]
> This is exactly what I plan to do.

Noice!

**Comment by Aizistral** [comment]
Now a little less of that Gagarin action going on, but with correct timing it should still be possible to gain significant acceleration after jumping and opening wings.
