### ISSUE TITLE
Neutral creatures and Ring of the Seven Curses

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#69]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.4.0
 * Curios API: 4.0.1.0
 * Patchouli: 1.16-42
 * Forge: 34.0.7

#### Description of a Bug:
When you taming the wolf and then wear RotSC tamed wolf naturally becomes aggresive to you. But you still can command him to sit which looks and feels a little strange. I guess it was not intended like that.

#### How to Reproduce:
1. Tame the wolf.
2. Wear Ring of the Seven Curses.
3. Command tamed wolf to seat with "Use Item/Place Block" Button.
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
I wonder if it makes sense to add exception for wolves so that they won't be angered against bearer of the Ring of the Seven Curses at all, as it also instantly angers other player's tamed wolves which isn't really a great design.

**Comment by Tillllt** [comment]
I think it will be reasonable. Are dolphins in exception already? Because they are not aggressive if you wear the ring. UPD: and pandas too.

**Comment by Tillllt** [comment]
Maybe then add an exception for bees too? Because at this moment it is inconvenient to keep an apiary.

**Comment by Tillllt** [comment]
But idk about golems. Actually it's fun, when you go to the village and that thing one hit kill you. And it's double fun when you make your own golem, take achievement "Hired help" and dying on the spot.

**Comment by Aizistral** [comment]
> I think it will be reasonable. Are dolphins in exception already? Because they are not aggressive if you wear the ring. UPD: and pandas too.

They just don't seem to implement IAngerable, so they just aren't affected by current implementation of the curse. It is possible to fix it, but I suppose it might be better to just leave it as is.

> Maybe then add an exception for bees too? Because at this moment it is inconvenient to keep an apiary.

Makes sense.

> And it's double fun when you make your own golem, take achievement "Hired help" and dying on the spot.

Well, isn't it a bruh moment.
Ideally though it should probably work so that player-made golems aren't immediately hostile towards bearer of the curse, but those spawned naturally still are. For same reasons as with wolves.

**Comment by Tillllt** [comment]
It's all sounds good. Still we have one thing there. Spiders and cave spiders is not aggressive to you on daylight, even with the cursed ring.
UPD: I guess i will change the title here since it's going further than just wolves. And it also need enhancement label now.

**Comment by Aizistral** [comment]
> Spiders and cave spiders is not aggressive to you on daylight, even with the cursed ring.

Spiders are not neutral mobs in general, so techically they should not fall under the the list of affected by this curse. I could make it so that they are affected, but don't see a significant point to be honest.

**Comment by Tillllt** [comment]
> Spiders are not neutral mobs in general

Didn't know this, OK. Actually it's hard to understand in game, is it hostile mob turning to neutral or neutral turning to hostile?

**Comment by Aizistral** [comment]
> Actually it's hard to understand in game, is it hostile mob turning to neutral or neutral turning to hostile?

Anything that doesn't act like a neutral mob under normal circumstances is usually a hostile one with some additional "ifs" wrapping their AI goals.

...with the exception of dolphins. Dolphins are weird.
