### ISSUE TITLE
Etherium Ore doesn't get accelerated in blast furnace, resulting half of the fuel value wasted

### ISSUE THREAD

**Issue by llssc** [Extegral/Enigmatic-Legacy#73]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.2.1
 * Curios API:  3.0.0.2
 * Patchouli: 1.16-39
 * Forge: 32.0.108

#### Description of a Bug:
Simply put, if you try to smelt 80 Etherium ores using a coal block, only 40 of them will be smelt. 
Or, smelt 8 Etherium ores using a coal, only 4 will be smelt.

This happens on BLAST furnace.

**Comment by Aizistral** [comment]
Etherium Ore supposedly takes twice longer than normal smelting recipes in both normal and blast furnace. That is intended.

Or is it so that smelting in regular furnace takes amount of time and fuel identical to that in a blast furnace?

**Comment by llssc** [comment]
Yes, I just realized it's the same in regular furnace as well. I guess you can close now.
