### ISSUE TITLE
Maybe remove knockback from Curse of Nemesis damage?

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#77]
**Provide a detailed and clear description of feature or change that you want to offer.**
In the title.
**Describe why you want this. If there's a reason.**
It's not very convenient to always fight like that (excepting against creepers).

**Comment by Aizistral** [comment]
I wanted it to work this way though. Knockback can be reduced or nullified through any equipment that has such trait, and I can also add a config option that would allow to disable it, but I'd like it to remain present by default.

**Comment by Tillllt** [comment]
OK then. If this is by design, i will just find my ways with that mechanic.
