### ISSUE TITLE
Nether Star

### ISSUE THREAD

**Issue by tikiMC** [Extegral/Enigmatic-Legacy#79]
I can only assume this is a mistake, why can I find 2-3 nether stars in a ruined portal, pillager outpost or dungeon chest. If this is intentional as you put it the loot tables, why?????

**Comment by Aizistral** [comment]
This is by no measure intentional, but there's no place where Enigmatic Legacy could possibly add Nether Stars to dungeon loot. Have you reproduced this with only Enigmatic Legacy, Patchouli and Curios? You can test the loot by using The One Box in creative mode, if anything.

**Comment by tikiMC** [comment]
then this is obviously a bug, if you go into the mods data folder > minecraft > loot_tables > chests you'll see the culprits. I am just running the 3 mods required as you said

**Comment by Aizistral** [comment]
Oh shit. These were loot tables overrides I used when debugging Forge issue before reporting to them, and I could swear I have deleted them from my workspace, but somehow they are still there and have gotten into releases. Will make a patch later today to fix this.

**Comment by tikiMC** [comment]
this is easy to fix with datapacks as I did but I have just enough resources installed in the modpack and it bugs me that it still says that I should be able to find nether stars in those 3 structures

**Comment by tikiMC** [comment]
kk thanks!!
