### ISSUE TITLE
Glass Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [Extegral/Enigmatic-Legacy#8]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: v1.4
 * Curios API: v1.0.2
 * Forge: v28.1.44

#### Description of a Bug:
- Placing any glass-like block, including End Crystal Gems, Dark Beacons, and Runic Glass, underwater will render incorrectly underwater, with water flowing down the sides. Glass should render similarly to Minecraft Glass
- Custom signs also can only be placed on the ground, but not on walls.

#### Image:
![2019-10-12_01 42 13](https://user-images.githubusercontent.com/12000593/66696426-8e1a1d80-ec91-11e9-88c9-778be85f5aa7.png)

**Comment by Extegral** [comment]
These are added by Forbidden and Arcanus, not by my mod. Report it to their [issue tracker](https://github.com/stal111/Forbidden-Arcanus/issues).

**Comment by WenXin20** [comment]
Whoops, sorry about that!
