### ISSUE TITLE
Changing some config options for the Emblem of Monster Slayer causes Tooltip error.

### ISSUE THREAD

**Issue by Inpaladin** [Extegral/Enigmatic-Legacy#85]
Title.  Here's what my config looks like for the Emblem of Monster Slayer:
    # Whether or not Emblem of Monster Slayer should provide +1 Looting Level. [default: true, synchronized: yes]
    B:MonsterCharmBonusLooting=false

    # Whether or not Emblem of Monster Slayer should provide double experience drop from monsters. [default: true, synchronized: yes]
    B:MonsterCharmDoubleXP=true

    # Damage bonus against agressive creatures for Emblem of Monster Slayer. Defined as percentage. [range: 0 ~ 1000, default: 10, synchronized: yes]
    I:MonsterCharmHostileDamage=0

    # Damage bonus against undead enemies for Emblem of Monster Slayer. Defined as percentage. [range: 0 ~ 1000, default: 25, synchronized: yes]
    I:MonsterCharmUndeadDamage=0

![image](https://user-images.githubusercontent.com/59532097/95980596-3b0e0580-0dd2-11eb-90cd-407ea26caf9b.png)
here's  the error, only shows up if I try pressing shift while hovering over said charm.

curios version 4.0.2.0
forge version 34.1.0
enigmatic legacy version 2.6.0

**Comment by Aizistral** [comment]
Really isn't even because of config alterations, I just misassigned some config objects in item class which causes NullPointerException in a wide variety of situations. Too bad
