### ISSUE TITLE
Ticking player entity issue

### ISSUE THREAD

**Issue by SpongeGuy** [Extegral/Enigmatic-Legacy#91]
#### Versions:
 * EnigmaticLegacy-2.7.0.jar
 * curios-forge-1.16.3-4.0.2.0.jar
 * Patchouli-1.16.2-47.jar
 * 1.16.3-forge-34.1.12

#### Description of the Bug:
I recently set up a modpack on techniclauncher to play with my friends and a server to go with it, but we soon realized enigmatic legacy was creating an issue where the game would check if each player had eaten a forbidden fruit every tick, crashing all players that are near each other.
We then isolated the mods above, getting rid of all other mods, and the game still crashed when players were near each other.

#### How to Reproduce:
1. Have two players with forge-34.1.12 clients with the mod versions above.
2. Create and launch a forge server with the same mods
3. Have the players try and play near each other on the server
4. Behold!

#### Logs:
These crash reports are with all the mods of our pack added:
ReaLord's perspective: [https://pastebin.pl/view/e9dd78bc](https://pastebin.pl/view/9ad0d914)
Tvvvvvvvvvv's perspective: [https://pastebin.pl/view/e9dd78bc](https://pastebin.pl/view/e9dd78bc)

This is from after we removed the mods to isolate the problem:
ReaLord's perspective: [https://pastebin.pl/view/342dce5d](https://pastebin.pl/view/342dce5d)

**Comment by Aizistral** [comment]
Duplicate of #90.
