### ISSUE TITLE
Ability to disable spawning with baubles

### ISSUE THREAD

**Issue by Goldenlion5648** [Extegral/Enigmatic-Legacy#93]
Would it be possible to add a config to disable spawning with the baubles when first making/ joining a world? 

I feel like some of the effects are a little powerful to have within seconds of starting a world.

**Comment by Aizistral** [comment]
Those options already exist. You just need to disable both Ring of the Seven Curses and Enigmatic Amulet (or whichever one you feel more concerned about) in `Accessibility Config` category within `enigmaticlegacy-common.omniconf` file. There currently are no other way of obtaining those items.
