### ISSUE TITLE
Keystone of Oblivion bug

### ISSUE THREAD

**Issue by 2el222** [Extegral/Enigmatic-Legacy#97]
Keystone of oblivion doesnt add items to its list.. happens very often, and even if u manage to somehow add an item, adding a new one deletes the one u added before

**Comment by Aizistral** [comment]
Please use bug report template and specify data requested there: [Click To Create](https://github.com/Extegral/Enigmatic-Legacy/issues/new?assignees=Extegral&labels=bug%2C+awaits+review&template=bug-report.md&title=)
