### ISSUE TITLE
Cursed Totem of Unliving

### ISSUE THREAD

**Issue by Gabo6480** [Extegral/Enigmatic-Legacy#99]
A cursed version of totem of undying that turns you into an undead when you die with it

Cons:
- Burn with sunlight (Wearing a helmet negates this at the price of damage to the helmet)
- Sink on water
- Healing harms you
- Villagers run away from you
- Unsatiable hunger
- Can only eat raw meat
- No saturation
- Wolves and Iron Golems hate you (Bonus damage to you)
- Smite deals bonus damage to you
- Reduced xp gain

Pros:
- Undead mobs are Neutral (Including the Wither)
- Harm heals you
- Immunity to poison
- No need to breathe
- Immunity to wither
- 2 armor points (Zombies have them too, so why not)
- Killing Villagers turns them into allied zombie villagers (?)

Obviously only obtainable by the cursed one, might be undone by applying weakness and eating a golden apple (?)

**Comment by Aizistral** [comment]
This is a big suggestion that I do not like as it stands, to be honest. I might adapt some parts of it as various items or mechanics in future, but so far I have a lot of other stuff coming right up, so...
